packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@hifi/core@https://codeload.github.com/rupurt/hifi/tar.gz/2541de2a480923b9101b6e8f9da11025253507ed#path:packages/core": true
  "@hifi/kinetic@https://codeload.github.com/rupurt/hifi/tar.gz/2541de2a480923b9101b6e8f9da11025253507ed#path:packages/kinetic": true
