packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@hifi/core@https://codeload.github.com/rupurt/hifi/tar.gz/54aae3b4f75b1bf4b163a21ab18d0af9641d09f6#path:packages/core": true
  "@hifi/kinetic@https://codeload.github.com/rupurt/hifi/tar.gz/54aae3b4f75b1bf4b163a21ab18d0af9641d09f6#path:packages/kinetic": true
