[package]
name = "rey-runtime"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
polars.workspace = true
rey-core = { path = "../rey-core" }
rey-dataframe = { path = "../rey-dataframe" }
rey-diff = { path = "../rey-diff" }
rey-environment = { path = "../rey-environment" }
rey-frontier = { path = "../rey-frontier" }
rey-mining = { path = "../rey-mining" }
rey-policy = { path = "../rey-policy" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
