[package]
name = "rey-proof"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
rey-core = { path = "../rey-core" }
rey-dataframe = { path = "../rey-dataframe" }
rey-diff = { path = "../rey-diff" }
rey-environment = { path = "../rey-environment" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
