import * as stylex from "@stylexjs/stylex";

const mono = 'var(--mono, "SFMono-Regular", Consolas, monospace)';
const display =
  'var(--display, "Arial Narrow", "Roboto Condensed", sans-serif)';

export const agentsStyles = stylex.create({
  page: { paddingTop: "clamp(46px, 6vw, 88px)" },
  hero: {
    alignItems: "end",
    display: "grid",
    gap: "clamp(42px, 8vw, 128px)",
    gridTemplateColumns: {
      default: "minmax(0, 1fr) minmax(430px, 0.76fr)",
      "@media (max-width: 980px)": "1fr",
    },
  },
  title: {
    fontSize: "clamp(3.5rem, 9vw, 9rem)",
    lineHeight: 0.82,
    marginBlock: "clamp(16px, 2vw, 28px)",
  },
  introduction: {
    fontFamily: mono,
    fontSize: "clamp(0.76rem, 1vw, 0.94rem)",
    lineHeight: 1.75,
    margin: 0,
    maxWidth: 720,
  },
  summary: {
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    margin: 0,
  },
  metric: {
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    borderRightColor: "var(--line)",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    padding: "22px 24px",
  },
  metricValue: {
    fontFamily: display,
    fontSize: "clamp(2.4rem, 4vw, 4.2rem)",
    fontWeight: 900,
    lineHeight: 1,
    margin: 0,
  },
  section: { marginTop: "clamp(74px, 9vw, 126px)" },
  sectionHeading: {
    alignItems: "end",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 20,
    gridTemplateColumns: {
      default: "72px minmax(0, 1fr) auto",
      "@media (max-width: 700px)": "52px 1fr",
    },
    paddingBottom: 17,
  },
  sectionIndex: {
    fontFamily: display,
    fontSize: "2.8rem",
    fontWeight: 900,
    lineHeight: 0.8,
  },
  kicker: { marginBlock: 0, marginBottom: 5 },
  empty: {
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "var(--muted)",
    marginTop: 28,
    padding: 48,
    textAlign: "center",
  },
  agentTable: {
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    marginTop: 28,
  },
  tableHeader: {
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    display: {
      default: "grid",
      "@media (max-width: 1080px)": "none",
    },
    gap: 18,
    gridTemplateColumns:
      "minmax(210px, 1.15fr) minmax(160px, 0.8fr) minmax(210px, 1fr) minmax(190px, 0.85fr) minmax(160px, 0.7fr)",
    padding: "12px 20px",
  },
  agentRow: {
    alignItems: "center",
    backgroundColor: {
      default: "var(--surface)",
      ":hover": "var(--surface-strong)",
    },
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 18,
    gridTemplateColumns: {
      default:
        "minmax(210px, 1.15fr) minmax(160px, 0.8fr) minmax(210px, 1fr) minmax(190px, 0.85fr) minmax(160px, 0.7fr)",
      "@media (max-width: 1080px)": "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 620px)": "1fr",
    },
    minWidth: 0,
    padding: "clamp(20px, 3vw, 34px)",
  },
  agentIdentity: {
    alignItems: "center",
    display: "flex",
    gap: 17,
    minWidth: 0,
  },
  agentOrdinal: {
    alignItems: "center",
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    display: "flex",
    flexShrink: 0,
    fontFamily: mono,
    fontSize: "0.66rem",
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  roleBinding: { display: "grid", gap: 8 },
  outputBinding: { display: "grid", gap: 7, minWidth: 0 },
  conformance: { display: "grid", gap: 7 },
  locate: {
    borderBottomColor: "currentColor",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    color: "inherit",
    fontFamily: mono,
    fontSize: "0.64rem",
    justifySelf: "start",
    letterSpacing: "0.08em",
    paddingBottom: 6,
    textDecoration: "none",
  },
  handoffGrid: {
    display: "grid",
    gap: 24,
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 800px)": "1fr",
    },
    marginTop: 28,
  },
  handoff: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    padding: "clamp(25px, 4vw, 45px)",
  },
  handoffRoute: {
    alignItems: "center",
    display: "flex",
    fontFamily: mono,
    fontSize: "0.6rem",
    gap: 10,
    marginBlock: 30,
  },
});
