import * as stylex from "@stylexjs/stylex";

const mono = 'var(--mono, "SFMono-Regular", Consolas, monospace)';
const display =
  'var(--display, "Arial Narrow", "Roboto Condensed", sans-serif)';

export const agentsStyles = stylex.create({
  page: { paddingTop: "clamp(46px, 6vw, 88px)" },
  section: { marginTop: "clamp(74px, 9vw, 126px)" },
  firstSection: { marginTop: 0 },
  sectionHeading: {
    alignItems: "end",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 20,
    gridTemplateColumns: {
      default: "72px minmax(0, 1fr) auto",
      "@media (max-width: 700px)": "52px 1fr",
    },
    paddingBottom: 17,
  },
  sectionIndex: {
    fontFamily: display,
    fontSize: "2.8rem",
    fontWeight: 900,
    lineHeight: 0.8,
  },
  kicker: { marginBlock: 0, marginBottom: 5 },
  empty: {
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "var(--muted)",
    marginTop: 28,
    padding: 48,
    textAlign: "center",
  },
  workflowGrammar: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(240px, 0.36fr) minmax(0, 1fr)",
      "@media (max-width: 840px)": "1fr",
    },
    marginTop: 28,
  },
  workflowGrammarLabel: {
    borderRightColor: "var(--line)",
    borderRightStyle: "solid",
    borderRightWidth: { default: 1, "@media (max-width: 840px)": 0 },
    display: "grid",
    gap: 10,
    padding: "clamp(22px, 3vw, 36px)",
  },
  workflowLanes: { display: "grid" },
  workflowLane: {
    alignItems: "center",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 20,
    gridTemplateColumns: {
      default: "84px minmax(0, 1fr)",
      "@media (max-width: 620px)": "1fr",
    },
    padding: "clamp(20px, 3vw, 34px)",
  },
  workflowOperations: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
  },
  workflowStep: { alignItems: "center", display: "inline-flex", gap: 12 },
  workflowArrow: { color: "var(--muted)", fontStyle: "normal" },
  taskTable: {
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    marginTop: 28,
  },
  taskTableHeader: {
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    display: {
      default: "grid",
      "@media (max-width: 1080px)": "none",
    },
    gap: 18,
    gridTemplateColumns:
      "minmax(240px, 1.2fr) minmax(145px, 0.65fr) minmax(170px, 0.75fr) minmax(160px, 0.7fr) minmax(160px, 0.65fr)",
    padding: "12px 20px",
  },
  taskRow: {
    alignItems: "center",
    backgroundColor: {
      default: "var(--surface)",
      ":hover": "var(--surface-strong)",
    },
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 18,
    gridTemplateColumns: {
      default:
        "minmax(240px, 1.2fr) minmax(145px, 0.65fr) minmax(170px, 0.75fr) minmax(160px, 0.7fr) minmax(160px, 0.65fr)",
      "@media (max-width: 1080px)": "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 620px)": "1fr",
    },
    minWidth: 0,
    padding: "clamp(20px, 3vw, 34px)",
  },
  taskIdentity: {
    alignItems: "start",
    display: "flex",
    gap: 17,
    minWidth: 0,
  },
  taskObjective: { color: "var(--muted)", lineHeight: 1.45, marginBottom: 0 },
  ordinal: {
    alignItems: "center",
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    display: "flex",
    flexShrink: 0,
    fontFamily: mono,
    fontSize: "0.66rem",
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  operationBinding: { display: "grid", gap: 8 },
  artifactBinding: { display: "grid", gap: 7, minWidth: 0 },
  assignment: { display: "grid", gap: 8 },
  locate: {
    borderBottomColor: "currentColor",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    color: "inherit",
    fontFamily: mono,
    fontSize: "0.64rem",
    justifySelf: "start",
    letterSpacing: "0.08em",
    paddingBottom: 6,
    textDecoration: "none",
  },
  unlocated: { color: "var(--muted)" },
  runtimeBoundary: {
    alignItems: "center",
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    display: "grid",
    gap: 16,
    gridTemplateColumns: {
      default: "auto minmax(180px, 0.6fr) minmax(280px, 1fr)",
      "@media (max-width: 800px)": "1fr",
    },
    marginTop: 28,
    padding: "clamp(22px, 3vw, 34px)",
  },
  runtimeGrid: {
    display: "grid",
    gap: 20,
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 800px)": "1fr",
    },
    marginTop: 20,
  },
  runtimeCard: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    minWidth: 0,
    padding: "clamp(22px, 3vw, 34px)",
  },
  runtimeCardHeader: {
    alignItems: "start",
    display: "grid",
    gap: 16,
    gridTemplateColumns: "42px minmax(0, 1fr) auto",
  },
  runtimeIdentity: { display: "grid", gap: 8 },
  runtimeTitle: {
    fontFamily: display,
    fontSize: "clamp(1.6rem, 2.5vw, 2.3rem)",
    margin: 0,
    textTransform: "uppercase",
  },
  runtimePurpose: { color: "var(--muted)", lineHeight: 1.45, margin: 0 },
  runtimeStatus: {
    borderColor: "currentColor",
    borderStyle: "solid",
    borderWidth: 1,
    padding: "6px 8px",
  },
  runtimeFound: { color: "#237047" },
  runtimeMissing: { color: "#9a6411" },
  runtimeError: { color: "#b72d25" },
  runtimeDefinitions: {
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "grid",
    marginBlock: 24,
  },
  runtimeDefinition: {
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 14,
    gridTemplateColumns: "92px minmax(0, 1fr)",
    paddingBlock: 12,
  },
  runtimeTerm: {
    color: "var(--muted)",
    fontFamily: mono,
    fontSize: "0.64rem",
    letterSpacing: "0.08em",
  },
  runtimeValue: {
    fontFamily: mono,
    fontSize: "0.72rem",
    margin: 0,
    overflowWrap: "anywhere",
  },
  runtimeFooter: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 16,
    justifyContent: "space-between",
  },
});
