import * as stylex from "@stylexjs/stylex";

const mono = 'var(--mono, "SFMono-Regular", Consolas, monospace)';
const display =
  'var(--display, "Arial Narrow", "Roboto Condensed", sans-serif)';

export const cadenceStyles = stylex.create({
  page: { paddingTop: "clamp(46px, 6vw, 88px)" },
  section: { marginTop: "clamp(72px, 9vw, 124px)" },
  firstSection: { marginTop: 0 },
  sectionHeading: {
    alignItems: "end",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 20,
    gridTemplateColumns: {
      default: "72px minmax(0, 1fr) auto",
      "@media (max-width: 700px)": "52px 1fr",
    },
    paddingBottom: 17,
  },
  sectionIndex: {
    fontFamily: display,
    fontSize: "2.8rem",
    fontWeight: 900,
    lineHeight: 0.8,
  },
  kicker: { marginBlock: 0, marginBottom: 5 },
  lanes: {
    display: "grid",
    gap: "clamp(24px, 4vw, 52px)",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 980px)": "1fr",
    },
    marginTop: 28,
  },
  lane: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    minWidth: 0,
  },
  laneHeader: {
    alignItems: "center",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    justifyContent: "space-between",
    padding: "22px 24px",
  },
  laneClock: { color: "var(--muted)" },
  completeness: {
    borderColor: "currentColor",
    borderStyle: "solid",
    borderWidth: 1,
    padding: "7px 9px",
  },
  complete: { color: "#237047" },
  bounded: { color: "#89540d" },
  emptyLane: {
    color: "var(--muted)",
    padding: 42,
    textAlign: "center",
  },
  tickList: { listStyle: "none", margin: 0, padding: 0 },
  tick: {
    borderBottomColor: "var(--line-soft)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gridTemplateColumns: "58px minmax(0, 1fr)",
    minWidth: 0,
  },
  tickRail: {
    alignItems: "center",
    borderRightColor: "var(--line)",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    display: "flex",
    flexDirection: "column",
    fontFamily: mono,
    fontSize: "0.6rem",
    gap: 9,
    paddingTop: 25,
  },
  tickBody: { minWidth: 0, padding: "22px 24px 25px" },
  tickMeta: {
    color: "var(--muted)",
    display: "flex",
    flexWrap: "wrap",
    gap: "7px 15px",
  },
  tickKind: { color: "var(--rey-foreground)" },
  tickBinding: {
    alignItems: "center",
    borderTopColor: "var(--line-soft)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    flexWrap: "wrap",
    fontFamily: mono,
    fontSize: "0.62rem",
    gap: 15,
    justifyContent: "space-between",
    marginTop: 18,
    paddingTop: 13,
  },
  commitLink: {
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    color: "inherit",
    textDecoration: "none",
  },
  laneOmissions: {
    backgroundColor: "color-mix(in srgb, #b57417 9%, transparent)",
    color: "#704609",
    fontFamily: mono,
    fontSize: "0.62rem",
    lineHeight: 1.5,
    listStyle: "none",
    margin: 0,
    padding: "14px 24px",
  },
  scheduleGrid: {
    display: "grid",
    gap: 24,
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 850px)": "1fr",
    },
    marginTop: 28,
  },
  scheduleCard: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gridTemplateColumns: {
      default: "150px minmax(0, 1fr)",
      "@media (max-width: 520px)": "1fr",
    },
  },
  scheduleDial: {
    alignItems: "center",
    borderRightColor: "var(--line)",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    display: "flex",
    flexDirection: "column",
    fontFamily: display,
    fontSize: "2.7rem",
    fontWeight: 900,
    justifyContent: "center",
    minHeight: 210,
  },
  scheduleBody: { padding: "26px 28px" },
  scheduleId: { color: "var(--muted)" },
  scheduleDefinitions: {
    display: "grid",
    fontFamily: mono,
    fontSize: "0.62rem",
    gap: 8,
    marginBottom: 0,
    marginTop: 20,
  },
  boundary: { marginBottom: 30 },
  boundaryGrid: {
    display: "grid",
    gap: 0,
    gridTemplateColumns: {
      default: "minmax(0, 1fr) minmax(360px, 0.8fr)",
      "@media (max-width: 850px)": "1fr",
    },
    marginTop: 28,
  },
  boundaryStatement: {
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    fontFamily: mono,
    lineHeight: 1.8,
    margin: 0,
    padding: "clamp(28px, 5vw, 60px)",
  },
  omissionList: {
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    fontFamily: mono,
    fontSize: "0.68rem",
    lineHeight: 1.6,
    listStyle: "square",
    margin: 0,
    padding: "clamp(28px, 5vw, 60px)",
  },
});
