import * as stylex from "@stylexjs/stylex";

const mono = 'var(--mono, "SFMono-Regular", Consolas, monospace)';
const display =
  'var(--display, "Arial Narrow", "Roboto Condensed", sans-serif)';

export const channelsStyles = stylex.create({
  page: { display: "grid", gap: 92, paddingTop: "clamp(46px, 6vw, 88px)" },
  section: { minWidth: 0 },
  heading: {
    alignItems: "end",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 20,
    gridTemplateColumns: {
      default: "72px minmax(0, 1fr) auto",
      "@media (max-width: 760px)": "52px minmax(0, 1fr)",
    },
    paddingBottom: 17,
  },
  index: {
    fontFamily: display,
    fontSize: "2.8rem",
    fontWeight: 900,
    lineHeight: 0.8,
  },
  kicker: { marginBlock: 0, marginBottom: 5 },
  detail: {
    color: "var(--muted)",
    gridColumn: { default: "auto", "@media (max-width: 760px)": "1 / -1" },
    textAlign: { default: "right", "@media (max-width: 760px)": "left" },
  },
  planeGrid: {
    display: "grid",
    gap: 1,
    gridTemplateColumns: {
      default: "repeat(3, minmax(0, 1fr))",
      "@media (max-width: 900px)": "1fr",
    },
    marginTop: 20,
  },
  plane: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 10,
    minWidth: 0,
    overflowWrap: "anywhere",
    padding: 20,
  },
  stack: { display: "grid", gap: 6 },
  table: {
    "--kinetic-dense-table-cell-padding": "18px 20px",
    marginTop: 20,
  },
  row: {
    backgroundColor: {
      default: "var(--surface)",
      ":hover": "var(--surface-strong)",
    },
  },
  topologyFacts: {
    display: "grid",
    gap: 16,
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 760px)": "1fr",
    },
    marginTop: 20,
  },
  fact: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 8,
    padding: 20,
  },
  deltaGrid: {
    display: "grid",
    gap: 16,
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 900px)": "1fr",
    },
    marginTop: 20,
  },
  deltaPanel: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 14,
    minWidth: 0,
    overflowWrap: "anywhere",
    padding: 20,
  },
  changeList: {
    display: "grid",
    gap: 12,
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  warning: {
    backgroundColor: "color-mix(in srgb, #b57417 10%, var(--surface))",
    borderColor: "#b57417",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 8,
    marginTop: 20,
    padding: 20,
  },
  warningNetwork: {
    backgroundColor: "color-mix(in srgb, #b72d25 10%, var(--surface))",
    borderColor: "#b72d25",
  },
  editor: { display: "grid", gap: 12, marginTop: 16 },
  editorLabel: {
    fontFamily: mono,
    fontSize: "0.68rem",
    letterSpacing: "0.08em",
  },
  textarea: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "inherit",
    fontFamily: mono,
    fontSize: "0.78rem",
    lineHeight: 1.55,
    minHeight: 440,
    padding: 18,
    resize: "vertical",
  },
  editorFooter: {
    alignItems: "center",
    display: "flex",
    gap: 18,
    justifyContent: "space-between",
  },
  submit: {
    backgroundColor: {
      default: "var(--rey-foreground)",
      ":disabled": "var(--line)",
    },
    borderWidth: 0,
    color: "var(--rey-background)",
    cursor: { default: "pointer", ":disabled": "not-allowed" },
    fontFamily: mono,
    fontSize: "0.68rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    paddingBlock: 14,
    paddingInline: 18,
  },
  error: {
    borderLeftColor: "#b72d25",
    borderLeftStyle: "solid",
    borderLeftWidth: 4,
    color: "#b72d25",
    fontFamily: mono,
    fontSize: "0.72rem",
    marginBlock: 14,
    padding: 12,
  },
});
