import * as stylex from "@stylexjs/stylex";

const calibrate = stylex.keyframes({
  to: { transform: "rotate(360deg)" },
});

const mono = 'var(--mono, "SFMono-Regular", Consolas, monospace)';
const display =
  'var(--display, "Arial Narrow", "Roboto Condensed", sans-serif)';

export const environmentStyles = stylex.create({
  focusable: {
    color: "inherit",
    font: "inherit",
    outlineColor: {
      default: "transparent",
      ":focus-visible": "var(--rey-accent, #ff553e)",
    },
    outlineOffset: 3,
    outlineStyle: "solid",
    outlineWidth: {
      default: 0,
      ":focus-visible": 3,
    },
  },
  environment: {
    "--display":
      '"Arial Narrow", "Roboto Condensed", "Helvetica Neue", sans-serif',
    "--line": "color-mix(in srgb, var(--rey-foreground) 27%, transparent)",
    "--line-soft": "color-mix(in srgb, var(--rey-foreground) 11%, transparent)",
    "--mono": '"SFMono-Regular", Consolas, "Liberation Mono", monospace',
    "--muted": "color-mix(in srgb, var(--rey-foreground) 62%, transparent)",
    "--surface": "color-mix(in srgb, var(--rey-background) 91%, white)",
    "--surface-strong": "color-mix(in srgb, var(--rey-background) 82%, white)",
    backgroundColor: "var(--rey-background)",
    backgroundImage:
      "linear-gradient(90deg, var(--line-soft) 1px, transparent 1px), linear-gradient(var(--line-soft) 1px, transparent 1px)",
    backgroundSize: "48px 48px",
    color: "var(--rey-foreground)",
    minHeight: "100vh",
  },
  environmentViewport: {
    display: "flex",
    flexDirection: "column",
    height: "100dvh",
    minHeight: 0,
    overflow: "hidden",
  },
  viewportFixed: { flexShrink: 0 },
  topbar: {
    alignItems: "stretch",
    backdropFilter: "blur(14px)",
    backgroundColor:
      "color-mix(in srgb, var(--rey-background) 92%, transparent)",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(220px, 1fr) auto minmax(220px, 1fr)",
      "@media (max-width: 1050px)":
        "minmax(170px, 1fr) auto minmax(170px, 1fr)",
      "@media (max-width: 760px)": "1fr",
    },
    minHeight: 72,
    position: "sticky",
    top: 0,
    zIndex: 20,
  },
  wordmark: {
    alignItems: "center",
    borderRightColor: "var(--line)",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    display: "flex",
    gap: 14,
    paddingBlock: 10,
    paddingInline: 24,
    textDecoration: "none",
  },
  wordmarkMark: {
    alignItems: "center",
    backgroundColor: "var(--rey-foreground)",
    borderRadius: 2,
    color: "var(--rey-background)",
    display: "flex",
    fontFamily: display,
    fontSize: "1.55rem",
    fontWeight: 900,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  wordmarkText: { display: "grid" },
  wordmarkStrong: {
    fontFamily: display,
    fontSize: "1.1rem",
    fontWeight: 900,
    letterSpacing: "0.08em",
    lineHeight: 1,
  },
  micro: {
    fontFamily: mono,
    fontSize: "0.59rem",
    letterSpacing: "0.11em",
    textTransform: "uppercase",
  },
  wordmarkSmall: {
    color: "var(--muted)",
    marginTop: 4,
  },
  primaryNav: {
    alignItems: "stretch",
    borderTopColor: {
      default: "transparent",
      "@media (max-width: 760px)": "var(--line)",
    },
    borderTopStyle: "solid",
    borderTopWidth: {
      default: 0,
      "@media (max-width: 760px)": 1,
    },
    display: "flex",
    gridColumn: {
      default: "auto",
      "@media (max-width: 760px)": "1 / -1",
    },
    gridRow: { default: "auto", "@media (max-width: 760px)": 2 },
    justifyContent: "center",
    order: { default: 0, "@media (max-width: 760px)": 3 },
  },
  navLink: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": "color-mix(in srgb, white 21%, transparent)",
    },
    borderRightColor: "var(--line)",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    display: "flex",
    flex: { default: "none", "@media (max-width: 760px)": 1 },
    fontFamily: mono,
    fontSize: "0.7rem",
    gap: 11,
    justifyContent: {
      default: "flex-start",
      "@media (max-width: 760px)": "center",
    },
    letterSpacing: "0.08em",
    minHeight: { default: "auto", "@media (max-width: 760px)": 48 },
    paddingBlock: 0,
    paddingInline: { default: 28, "@media (max-width: 760px)": 15 },
    position: "relative",
    textDecoration: "none",
    textTransform: "uppercase",
  },
  navLinkActive: {
    "::after": {
      backgroundColor: "var(--rey-accent)",
      bottom: -1,
      content: '""',
      height: 4,
      left: 0,
      position: "absolute",
      right: 0,
    },
  },
  navCount: {
    alignItems: "center",
    borderColor: "var(--line)",
    borderRadius: 999,
    borderStyle: "solid",
    borderWidth: 1,
    display: "inline-flex",
    fontSize: "0.55rem",
    height: 22,
    justifyContent: "center",
    minWidth: 22,
    paddingInline: 6,
  },
  statusDot: {
    backgroundColor: "#237047",
    borderRadius: "50%",
    boxShadow: "0 0 0 3px color-mix(in srgb, #237047 20%, transparent)",
    display: "inline-block",
    height: 7,
    width: 7,
  },
  statusDotBlocked: {
    backgroundColor: "#b57417",
    boxShadow: "0 0 0 3px color-mix(in srgb, #b57417 20%, transparent)",
  },
  coordinateRail: {
    alignItems: "center",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: { default: "flex", "@media (max-width: 760px)": "none" },
    gap: 12,
    minHeight: 32,
    paddingInline: 24,
  },
  railLine: {
    backgroundColor: "var(--line)",
    flex: 1,
    height: 1,
  },
  page: {
    marginInline: "auto",
    maxWidth: 1600,
    paddingBlock: "clamp(38px, 6vw, 94px)",
    paddingInline: {
      default: "clamp(22px, 5vw, 80px)",
      "@media (max-width: 760px)": 16,
    },
  },
  heroGrid: {
    alignItems: "center",
    display: "grid",
    gap: "clamp(42px, 7vw, 112px)",
    gridTemplateColumns: {
      default: "minmax(0, 0.9fr) minmax(470px, 1.1fr)",
      "@media (max-width: 1050px)": "1fr",
    },
    minHeight: "min(790px, calc(100vh - 104px))",
    paddingTop: { default: 0, "@media (max-width: 1050px)": 35 },
  },
  displayTitle: {
    fontFamily: display,
    fontStretch: "condensed",
    fontWeight: 900,
    letterSpacing: "-0.075em",
    margin: 0,
    textTransform: "uppercase",
  },
  heroTitle: {
    fontSize: {
      default: "clamp(5rem, 10vw, 10.5rem)",
      "@media (max-width: 760px)": "clamp(4.1rem, 22vw, 7rem)",
    },
    lineHeight: 0.7,
  },
  heroTitleAccent: {
    color: "var(--rey-accent)",
    display: "block",
    fontSize: "0.43em",
    letterSpacing: "-0.025em",
    marginTop: "0.46em",
  },
  eyebrow: {
    alignItems: "center",
    display: "flex",
    gap: 10,
    marginBlock: 0,
    marginBottom: 28,
    "::before": {
      backgroundColor: "var(--rey-accent)",
      content: '""',
      height: 3,
      width: 38,
    },
  },
  heroIntro: {
    fontSize: "clamp(1rem, 1.4vw, 1.24rem)",
    lineHeight: 1.55,
    marginBlock: 46,
    marginBottom: 34,
    maxWidth: 610,
  },
  heroLinks: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 22,
  },
  controlLabel: {
    fontFamily: mono,
    fontSize: "0.64rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  mechanicalLink: {
    borderBottomColor: "var(--rey-foreground)",
    borderBottomStyle: "solid",
    borderBottomWidth: 2,
    paddingBlock: 10,
    paddingBottom: 8,
    textDecoration: "none",
  },
  mechanicalArrow: {
    color: "var(--rey-accent)",
    display: "inline-block",
    marginLeft: 14,
    transform: { default: "none", ":hover": "translateX(5px)" },
    transitionDuration: {
      default: "140ms",
      "@media (prefers-reduced-motion: reduce)": "0.01ms",
    },
    transitionProperty: "transform",
    transitionTimingFunction: "ease",
  },
  portfolioMachine: {
    "--kinetic-surface-min-height": {
      default: "590px",
      "@media (max-width: 1050px)": "520px",
    },
    "--kinetic-surface-padding": {
      default: "clamp(34px, 5vw, 64px)",
      "@media (max-width: 760px)": "24px",
    },
    alignContent: "center",
    overflow: "hidden",
    "::before": {
      borderColor: "var(--line)",
      borderRadius: "50%",
      borderStyle: "solid",
      borderWidth: 1,
      content: '""',
      height: 12,
      left: 18,
      position: "absolute",
      top: 18,
      width: 12,
    },
    "::after": {
      borderColor: "var(--line)",
      borderRadius: "50%",
      borderStyle: "solid",
      borderWidth: 1,
      content: '""',
      height: 12,
      position: "absolute",
      right: 18,
      top: 18,
      width: 12,
    },
  },
  machineScale: {
    display: "flex",
    justifyContent: "space-between",
    left: "11%",
    position: "absolute",
    right: "11%",
    top: 54,
    "::before": {
      backgroundColor: "var(--line)",
      content: '""',
      height: 1,
      left: 0,
      position: "absolute",
      right: 0,
      top: 4,
    },
  },
  machineScaleTick: {
    backgroundColor: "var(--rey-background)",
    borderLeftColor: "var(--rey-foreground)",
    borderLeftStyle: "solid",
    borderLeftWidth: 1,
    height: 9,
    position: "relative",
  },
  machineReadout: {
    alignItems: "center",
    display: "grid",
    justifyItems: "center",
  },
  machineOutput: {
    color: "var(--rey-accent)",
    fontFamily: mono,
    fontSize: "clamp(5rem, 10vw, 9.5rem)",
    fontVariantNumeric: "tabular-nums",
    fontWeight: 900,
    letterSpacing: "-0.1em",
    lineHeight: 0.96,
    marginRight: "0.1em",
  },
  machineStatusGrid: {
    display: "grid",
    gap: 1,
    gridTemplateColumns: {
      default: "repeat(4, 1fr)",
      "@media (max-width: 760px)": "repeat(2, 1fr)",
    },
    marginTop: 42,
    width: "100%",
  },
  metricCell: {
    backgroundColor: "color-mix(in srgb, var(--rey-background) 70%, white)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    minWidth: 0,
    paddingBlock: 17,
    paddingInline: 13,
    textAlign: "left",
  },
  metricCellValue: {
    fontFamily: mono,
    fontSize: "1.45rem",
    fontVariantNumeric: "tabular-nums",
    marginTop: 8,
  },
  toneDanger: { color: "#b72d25" },
  toneWarning: { color: "#9a6411" },
  machinePlate: {
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    bottom: 24,
    display: "flex",
    gap: { default: 0, "@media (max-width: 760px)": 12 },
    justifyContent: "space-between",
    left: 24,
    paddingTop: 14,
    position: "absolute",
    right: 24,
  },
  metricStrip: {
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(4, 1fr)",
      "@media (max-width: 1050px)": "repeat(2, 1fr)",
      "@media (max-width: 760px)": "1fr",
    },
    marginBlock: 20,
    marginBottom: "clamp(70px, 10vw, 140px)",
  },
  metricPanel: {
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: {
      default: 0,
      "@media (max-width: 760px)": 1,
    },
    borderRightColor: "var(--line)",
    borderRightStyle: "solid",
    borderRightWidth: { default: 1, "@media (max-width: 760px)": 0 },
    display: "grid",
    minHeight: 190,
    padding: 24,
  },
  metricPanelValue: {
    alignSelf: "end",
    fontFamily: display,
    fontSize: "clamp(2.8rem, 5vw, 5rem)",
    fontStretch: "condensed",
    fontVariantNumeric: "tabular-nums",
    fontWeight: 900,
    letterSpacing: "-0.06em",
  },
  muted: { color: "var(--muted)" },
  metricPanelDetail: { marginTop: 8 },
  sectionSpacing: { marginTop: "clamp(68px, 9vw, 120px)" },
  sectionHeading: {
    alignItems: { default: "end", "@media (max-width: 760px)": "start" },
    borderBottomColor: "var(--rey-foreground)",
    borderBottomStyle: "solid",
    borderBottomWidth: 2,
    display: "grid",
    gap: 22,
    gridTemplateColumns: {
      default: "55px 1fr auto",
      "@media (max-width: 760px)": "34px 1fr",
    },
    marginBottom: 28,
    paddingBottom: 18,
  },
  sectionIndex: {
    color: "var(--rey-accent)",
    fontFamily: mono,
    fontSize: "1.3rem",
    fontWeight: 900,
  },
  sectionKicker: { marginBlock: 0, marginBottom: 5 },
  sectionTitle: {
    fontFamily: display,
    fontSize: "clamp(1.8rem, 3vw, 3rem)",
    fontStretch: "condensed",
    fontWeight: 900,
    letterSpacing: "-0.04em",
    margin: 0,
    textTransform: "uppercase",
  },
  sectionDetail: {
    color: "var(--muted)",
    gridColumn: { default: "auto", "@media (max-width: 760px)": 2 },
    textAlign: { default: "right", "@media (max-width: 760px)": "left" },
  },
  attentionTable: {
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
  },
  attentionGrid: {
    alignItems: { default: "center", "@media (max-width: 760px)": "start" },
    display: "grid",
    gap: 18,
    gridTemplateColumns: {
      default: "0.7fr 1.7fr 1.5fr 0.8fr 0.45fr",
      "@media (max-width: 760px)": "1fr auto",
    },
    paddingBlock: 15,
    paddingInline: 18,
  },
  attentionHeader: {
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    display: { default: "grid", "@media (max-width: 760px)": "none" },
    fontFamily: mono,
    fontSize: "0.56rem",
    letterSpacing: "0.1em",
  },
  attentionRow: {
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    minHeight: 66,
  },
  attentionText: {
    fontFamily: mono,
    fontSize: "0.67rem",
    letterSpacing: "0.05em",
  },
  attentionAction: { color: "var(--rey-accent)" },
  attentionSubject: {
    fontWeight: 700,
    gridColumn: { default: "auto", "@media (max-width: 760px)": "1 / -1" },
    overflowWrap: "anywhere",
  },
  attentionReason: {
    color: "var(--muted)",
    gridColumn: { default: "auto", "@media (max-width: 760px)": "1 / -1" },
    textTransform: "uppercase",
  },
  readinessExcluded: { opacity: 0.58 },
  twoColumnGrid: {
    display: "grid",
    gap: 18,
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 760px)": "1fr",
    },
  },
  workloadCard: {
    backgroundColor: "var(--surface)",
    backgroundImage:
      "linear-gradient(90deg, var(--line-soft) 1px, transparent 1px), linear-gradient(var(--line-soft) 1px, transparent 1px)",
    backgroundSize: "24px 24px",
    borderColor: "var(--line)",
    borderRadius: "var(--rey-radius)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: {
      default:
        "0 calc(var(--kinetic-travel) * 0.45) 0 color-mix(in srgb, var(--rey-foreground) 28%, transparent), 0 9px 18px color-mix(in srgb, var(--rey-foreground) 9%, transparent)",
      ":hover":
        "0 calc(var(--kinetic-travel) * 0.7) 0 color-mix(in srgb, var(--rey-foreground) 30%, transparent), 0 14px 25px color-mix(in srgb, var(--rey-foreground) 13%, transparent)",
      ":active":
        "inset 0 3px 8px color-mix(in srgb, var(--rey-foreground) 15%, transparent)",
    },
    display: "flex",
    flexDirection: "column",
    minHeight: 390,
    overflow: "hidden",
    padding: 24,
    position: "relative",
    textDecoration: "none",
    transform: {
      default: "none",
      ":hover": "translateY(-2px)",
      ":active":
        "translateY(calc(var(--kinetic-travel) * var(--kinetic-actuation)))",
    },
    transitionDuration: {
      default: "120ms",
      "@media (prefers-reduced-motion: reduce)": "0.01ms",
    },
    transitionProperty: "transform, box-shadow",
    transitionTimingFunction: "ease",
  },
  draftCard: {
    backgroundColor: "color-mix(in srgb, var(--rey-accent) 8%, var(--surface))",
    borderStyle: "dashed",
  },
  cardIndex: { alignItems: "center", display: "flex", gap: 12 },
  cardJourney: { color: "var(--rey-accent)", fontWeight: 900 },
  cardLine: { backgroundColor: "var(--line)", flex: 1, height: 1 },
  cardTitle: {
    fontFamily: display,
    fontSize: "clamp(1.65rem, 3vw, 2.8rem)",
    fontStretch: "condensed",
    fontWeight: 900,
    letterSpacing: "-0.045em",
    lineHeight: 0.98,
    marginBlock: 45,
    marginBottom: 10,
    overflowWrap: "anywhere",
  },
  cardDescription: {
    color: "var(--muted)",
    lineHeight: 1.45,
    margin: 0,
  },
  cardProgress: {
    alignItems: "center",
    display: "grid",
    gap: 15,
    gridTemplateColumns: "1fr auto",
    marginTop: 35,
  },
  progressTrack: {
    backgroundColor:
      "color-mix(in srgb, var(--rey-foreground) 10%, transparent)",
    height: 7,
    overflow: "hidden",
  },
  progressFill: {
    backgroundColor: "var(--rey-foreground)",
    display: "block",
    height: "100%",
  },
  progressFailure: { backgroundColor: "#b72d25" },
  progressStale: { backgroundColor: "#b57417" },
  progressPercent: { fontFamily: mono, fontSize: "0.75rem" },
  cardDefinitions: {
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    marginBlock: 24,
    marginBottom: 0,
  },
  cardDefinition: {
    borderBottomColor: "var(--line-soft)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 14,
    gridTemplateColumns: "95px 1fr",
    paddingBlock: 9,
  },
  cardTerm: { color: "var(--muted)", fontFamily: mono, fontSize: "0.58rem" },
  cardValue: {
    fontFamily: mono,
    fontSize: "0.58rem",
    margin: 0,
    overflowWrap: "anywhere",
    textAlign: "right",
  },
  cardOpen: {
    color: "var(--rey-accent)",
    marginTop: "auto",
    paddingTop: 24,
  },
  draftMechanism: {
    alignItems: "center",
    display: "flex",
    fontFamily: mono,
    fontSize: "0.55rem",
    gap: 10,
    letterSpacing: "0.08em",
    marginBlock: 32,
    marginBottom: 0,
  },
  draftLine: {
    borderTopColor: "var(--line)",
    borderTopStyle: "dashed",
    borderTopWidth: 1,
    flex: 1,
  },
  emptySurface: {
    alignItems: "center",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    fontFamily: mono,
    fontSize: "0.68rem",
    gap: 20,
    justifyContent: "center",
    letterSpacing: "0.08em",
    minHeight: 130,
  },
  emptyLine: { backgroundColor: "#237047", height: 2, width: 42 },
  pageHeader: {
    alignItems: { default: "end", "@media (max-width: 760px)": "start" },
    display: "flex",
    flexDirection: { default: "row", "@media (max-width: 760px)": "column" },
    gap: { default: 0, "@media (max-width: 760px)": 48 },
    justifyContent: "space-between",
    marginBottom: 110,
  },
  pageTitle: {
    fontSize: "clamp(3.8rem, 8vw, 8rem)",
    lineHeight: 0.8,
  },
  catalogGauge: {
    borderLeftColor: "var(--line)",
    borderLeftStyle: "solid",
    borderLeftWidth: 1,
    display: "grid",
    minWidth: 240,
    paddingBlock: 8,
    paddingLeft: 28,
    width: { default: "auto", "@media (max-width: 760px)": "100%" },
  },
  catalogValue: {
    color: "var(--rey-accent)",
    fontFamily: display,
    fontSize: "4rem",
    fontWeight: 900,
    lineHeight: 1,
  },
  backLink: {
    display: "inline-block",
    marginBottom: 72,
    textDecoration: "none",
  },
  detailTitle: { fontSize: "1.2rem", marginBlock: 28, marginBottom: 0 },
  detailGrid: {
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(4, 1fr)",
      "@media (max-width: 1050px)": "repeat(2, 1fr)",
      "@media (max-width: 760px)": "1fr",
    },
    marginTop: 64,
  },
  detailPanel: {
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: {
      default: 0,
      "@media (max-width: 760px)": 1,
    },
    borderRightColor: "var(--line)",
    borderRightStyle: "solid",
    borderRightWidth: { default: 1, "@media (max-width: 760px)": 0 },
    display: "grid",
    minHeight: 140,
    padding: 22,
  },
  detailPanelValue: {
    alignSelf: "end",
    fontFamily: display,
    fontSize: "clamp(1.35rem, 2.2vw, 2.3rem)",
    fontStretch: "condensed",
    fontWeight: 900,
    lineHeight: 0.95,
  },
  accent: { color: "var(--rey-accent)" },
  evidenceSurface: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    padding: "clamp(24px, 4vw, 52px)",
  },
  conformanceHeading: {
    alignItems: "end",
    display: "flex",
    fontFamily: mono,
    fontSize: "0.67rem",
    justifyContent: "space-between",
    letterSpacing: "0.08em",
  },
  conformanceValue: { fontSize: "2.6rem", letterSpacing: "-0.07em" },
  conformanceTrack: { height: 18, marginBlock: 24, marginBottom: 16 },
  conformanceFill: { backgroundColor: "var(--rey-accent)" },
  conformanceMeta: {
    display: "flex",
    flexWrap: "wrap",
    fontFamily: mono,
    fontSize: "0.59rem",
    gap: 24,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
  },
  panelTitle: {
    borderBottomColor: "var(--rey-foreground)",
    borderBottomStyle: "solid",
    borderBottomWidth: 2,
    marginBottom: 22,
    paddingBottom: 15,
  },
  definition: {
    borderBottomColor: "var(--line-soft)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: { default: 30, "@media (max-width: 760px)": 8 },
    gridTemplateColumns: {
      default: "180px minmax(0, 1fr)",
      "@media (max-width: 760px)": "1fr",
    },
    paddingBlock: 15,
  },
  definitionValue: { fontSize: "0.88rem", overflowWrap: "anywhere" },
  monoValue: { fontFamily: mono, fontSize: "0.71rem", fontWeight: 500 },
  miningPanel: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: {
      default: "repeat(5, 1fr)",
      "@media (max-width: 1050px)": "repeat(3, 1fr)",
      "@media (max-width: 760px)": "1fr",
    },
  },
  miningTitle: {
    gridColumn: { default: "1 / -1", "@media (max-width: 760px)": "auto" },
  },
  systemPage: {
    alignContent: "center",
    display: "grid",
    justifyItems: "start",
    marginInline: "auto",
    maxWidth: 1200,
    minHeight: "calc(100vh - 105px)",
    padding: 60,
  },
  systemTitle: {
    fontSize: "clamp(4rem, 9vw, 8rem)",
    lineHeight: 0.8,
  },
  systemError: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    fontFamily: mono,
    fontSize: "0.7rem",
    marginTop: 38,
    maxWidth: "100%",
    overflow: "auto",
    padding: 22,
  },
  loader: {
    alignItems: "center",
    display: "flex",
    fontFamily: mono,
    fontSize: "0.7rem",
    gap: 18,
    letterSpacing: "0.08em",
  },
  loaderSpinner: {
    animationDuration: "900ms",
    animationIterationCount: "infinite",
    animationName: {
      default: calibrate,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    animationTimingFunction: "steps(4, end)",
    borderColor: "color-mix(in srgb, var(--rey-foreground) 16%, transparent)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderTopColor: "var(--rey-accent)",
    borderWidth: 7,
    height: 42,
    width: 42,
  },
  footer: {
    alignItems: {
      default: "center",
      "@media (max-width: 760px)": "flex-start",
    },
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    flexDirection: { default: "row", "@media (max-width: 760px)": "column" },
    gap: 28,
    justifyContent: "space-between",
    minHeight: 54,
    paddingBlock: 12,
    paddingInline: 24,
  },
  footerLink: {
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    color: "inherit",
    textDecoration: "none",
  },
});
