import * as stylex from "@stylexjs/stylex";

const calibrate = stylex.keyframes({
  to: { transform: "rotate(360deg)" },
});

const mono = 'var(--mono, "SFMono-Regular", Consolas, monospace)';
const display =
  'var(--display, "Arial Narrow", "Roboto Condensed", sans-serif)';

export const environmentStyles = stylex.create({
  focusable: {
    color: "inherit",
    font: "inherit",
    outlineColor: {
      default: "transparent",
      ":focus-visible": "var(--rey-accent, #ff553e)",
    },
    outlineOffset: 3,
    outlineStyle: "solid",
    outlineWidth: {
      default: 0,
      ":focus-visible": 3,
    },
  },
  environment: {
    "--display":
      '"Arial Narrow", "Roboto Condensed", "Helvetica Neue", sans-serif',
    "--line": "color-mix(in srgb, var(--rey-foreground) 27%, transparent)",
    "--line-soft": "color-mix(in srgb, var(--rey-foreground) 11%, transparent)",
    "--mono": '"SFMono-Regular", Consolas, "Liberation Mono", monospace',
    "--muted": "color-mix(in srgb, var(--rey-foreground) 62%, transparent)",
    "--surface": "color-mix(in srgb, var(--rey-background) 91%, white)",
    "--surface-strong": "color-mix(in srgb, var(--rey-background) 82%, white)",
    backgroundColor: "var(--rey-background)",
    backgroundImage:
      "linear-gradient(90deg, var(--line-soft) 1px, transparent 1px), linear-gradient(var(--line-soft) 1px, transparent 1px)",
    backgroundSize: "48px 48px",
    color: "var(--rey-foreground)",
    boxSizing: "border-box",
    minHeight: "100vh",
    paddingBottom: 54,
  },
  environmentViewport: {
    display: "flex",
    flexDirection: "column",
    height: "100dvh",
    minHeight: 0,
    overflow: "hidden",
  },
  viewportFixed: { flexShrink: 0 },
  topbar: {
    alignItems: "stretch",
    backdropFilter: "blur(14px)",
    backgroundColor:
      "color-mix(in srgb, var(--rey-background) 92%, transparent)",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(220px, 1fr) auto minmax(220px, 1fr)",
      "@media (max-width: 1050px)":
        "minmax(170px, 1fr) auto minmax(170px, 1fr)",
      "@media (max-width: 760px)": "1fr",
    },
    minHeight: 72,
    position: "sticky",
    top: 0,
    zIndex: 20,
  },
  wordmark: {
    alignItems: "center",
    borderRightColor: "var(--line)",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    display: "flex",
    gap: 14,
    paddingBlock: 10,
    paddingInline: 24,
    textDecoration: "none",
  },
  wordmarkMark: {
    alignItems: "center",
    backgroundColor: "var(--rey-foreground)",
    borderRadius: 2,
    color: "var(--rey-background)",
    display: "flex",
    fontFamily: display,
    fontSize: "1.55rem",
    fontWeight: 900,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  wordmarkStrong: {
    fontFamily: display,
    fontSize: "1.1rem",
    fontWeight: 900,
    letterSpacing: "0.08em",
    lineHeight: 1,
  },
  micro: {
    fontFamily: mono,
    fontSize: "0.59rem",
    letterSpacing: "0.11em",
    textTransform: "uppercase",
  },
  primaryNav: {
    alignItems: "stretch",
    borderTopColor: {
      default: "transparent",
      "@media (max-width: 760px)": "var(--line)",
    },
    borderTopStyle: "solid",
    borderTopWidth: {
      default: 0,
      "@media (max-width: 760px)": 1,
    },
    display: { default: "flex", "@media (max-width: 760px)": "grid" },
    gridColumn: {
      default: "auto",
      "@media (max-width: 760px)": "1 / -1",
    },
    gridRow: { default: "auto", "@media (max-width: 760px)": 2 },
    justifyContent: "center",
    gridTemplateColumns: {
      default: "none",
      "@media (max-width: 760px)": "repeat(3, minmax(0, 1fr))",
    },
    order: { default: 0, "@media (max-width: 760px)": 3 },
  },
  navLink: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": "color-mix(in srgb, white 21%, transparent)",
    },
    borderRightColor: "var(--line)",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    display: "flex",
    flex: { default: "none", "@media (max-width: 760px)": "initial" },
    fontFamily: mono,
    fontSize: "0.7rem",
    gap: 11,
    justifyContent: {
      default: "flex-start",
      "@media (max-width: 760px)": "center",
    },
    letterSpacing: "0.08em",
    minHeight: { default: "auto", "@media (max-width: 760px)": 48 },
    paddingBlock: 0,
    paddingInline: { default: 22, "@media (max-width: 760px)": 9 },
    position: "relative",
    textDecoration: "none",
    textTransform: "uppercase",
  },
  navLinkActive: {
    "::after": {
      backgroundColor: "var(--rey-accent)",
      bottom: -1,
      content: '""',
      height: 4,
      left: 0,
      position: "absolute",
      right: 0,
    },
  },
  statusDot: {
    backgroundColor: "#237047",
    borderRadius: "50%",
    boxShadow: "0 0 0 3px color-mix(in srgb, #237047 20%, transparent)",
    display: "inline-block",
    height: 7,
    width: 7,
  },
  statusDotBlocked: {
    backgroundColor: "#b57417",
    boxShadow: "0 0 0 3px color-mix(in srgb, #b57417 20%, transparent)",
  },
  coordinateRail: {
    alignItems: "center",
    backdropFilter: "blur(14px)",
    backgroundColor:
      "color-mix(in srgb, var(--rey-background) 94%, transparent)",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: { default: "flex", "@media (max-width: 760px)": "none" },
    gap: 12,
    minHeight: 32,
    paddingInline: 24,
    position: "sticky",
    top: 72,
    zIndex: 19,
  },
  railLine: {
    backgroundColor: "var(--line)",
    flex: 1,
    height: 1,
  },
  page: {
    marginInline: "auto",
    maxWidth: 1600,
    paddingBlock: "clamp(38px, 6vw, 94px)",
    paddingInline: {
      default: "clamp(22px, 5vw, 80px)",
      "@media (max-width: 760px)": 16,
    },
  },
  heroGrid: {
    alignItems: "center",
    display: "grid",
    gap: "clamp(42px, 7vw, 112px)",
    gridTemplateColumns: {
      default: "minmax(0, 0.9fr) minmax(470px, 1.1fr)",
      "@media (max-width: 1050px)": "1fr",
    },
    minHeight: "min(790px, calc(100vh - 104px))",
    paddingTop: { default: 0, "@media (max-width: 1050px)": 35 },
  },
  environmentPage: {
    display: "grid",
    gap: "clamp(24px, 4vw, 52px)",
  },
  stateGood: { color: "#237047" },
  environmentDiffSurface: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    minWidth: 0,
  },
  environmentPanelHeader: {
    alignItems: { default: "end", "@media (max-width: 760px)": "start" },
    borderBottomColor: "var(--rey-foreground)",
    borderBottomStyle: "solid",
    borderBottomWidth: 2,
    display: "flex",
    flexDirection: { default: "row", "@media (max-width: 760px)": "column" },
    gap: 14,
    justifyContent: "space-between",
    paddingBlock: 22,
    paddingInline: 24,
  },
  environmentDiffDocument: {
    backgroundColor: "color-mix(in srgb, var(--rey-background) 94%, black)",
    minHeight: 250,
    overflowX: "auto",
    paddingBlock: 12,
  },
  environmentDiffEmpty: {
    alignItems: "center",
    color: "var(--muted)",
    display: "flex",
    fontFamily: mono,
    fontSize: "0.66rem",
    justifyContent: "center",
    minHeight: 220,
  },
  environmentDiffRow: {
    alignItems: "center",
    borderBottomColor: "var(--line-soft)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    fontFamily: mono,
    fontSize: "0.69rem",
    gridTemplateColumns: "44px 28px minmax(max-content, 1fr) auto",
    lineHeight: 1.55,
    minHeight: 38,
    paddingRight: 13,
  },
  environmentDiffInserted: {
    backgroundColor: "color-mix(in srgb, #237047 10%, transparent)",
    color: "#175c39",
  },
  environmentDiffDeleted: {
    backgroundColor: "color-mix(in srgb, #b72d25 9%, transparent)",
    color: "#8d251f",
  },
  environmentDiffContext: { color: "var(--muted)" },
  environmentLineNumber: {
    borderRightColor: "var(--line)",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    color: "var(--muted)",
    paddingRight: 10,
    textAlign: "right",
  },
  environmentDiffMarker: {
    fontSize: "0.9rem",
    fontWeight: 900,
    textAlign: "center",
  },
  environmentDiffCode: {
    color: "inherit",
    fontFamily: mono,
    paddingInline: 4,
    whiteSpace: "pre",
  },
  environmentAdmissionTag: {
    borderColor: "currentColor",
    borderRadius: 999,
    borderStyle: "solid",
    borderWidth: 1,
    fontSize: "0.5rem",
    letterSpacing: "0.08em",
    marginLeft: 24,
    opacity: 0.65,
    paddingBlock: 2,
    paddingInline: 7,
    textTransform: "uppercase",
  },
  environmentApplications: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    minWidth: 0,
  },
  environmentApplicationGroup: {
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
  },
  environmentApplicationGroupHeader: {
    alignItems: "center",
    backgroundColor: "var(--surface-strong)",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    justifyContent: "space-between",
    paddingBlock: 9,
    paddingInline: 16,
  },
  environmentApplicationGroupEmpty: {
    color: "var(--muted)",
    fontFamily: mono,
    fontSize: "0.59rem",
    letterSpacing: "0.11em",
    paddingBlock: 14,
    paddingInline: 16,
  },
  environmentApplicationNotFound: {
    backgroundColor: "color-mix(in srgb, #9a6411 8%, transparent)",
    color: "#7b510f",
  },
  environmentApplicationError: {
    backgroundColor: "color-mix(in srgb, #b72d25 9%, transparent)",
    color: "#8d251f",
  },
  environmentApplicationOutcome: {
    fontFamily: mono,
    fontSize: "0.5rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    marginLeft: 24,
    opacity: 0.8,
  },
  environmentApplicationDiffValue: {
    alignItems: "baseline",
    display: "grid",
    gap: 10,
    gridTemplateColumns: {
      default: "minmax(90px, 150px) minmax(180px, 1fr) auto",
      "@media (max-width: 760px)": "1fr",
    },
    minWidth: 0,
    paddingInline: 4,
  },
  environmentApplicationDiffPath: {
    color: "inherit",
    fontFamily: mono,
    overflowWrap: "anywhere",
  },
  environmentApplicationDiffGroups: {
    fontSize: "0.55rem",
    letterSpacing: "0.05em",
    opacity: 0.72,
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  environmentTopology: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    minWidth: 0,
  },
  environmentReferenceHeading: {
    alignItems: "start",
    display: "grid",
    gap: 18,
    gridTemplateColumns: "34px 1fr",
  },
  environmentTopologyGrid: {
    display: "grid",
    gap: 20,
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 760px)": "1fr",
    },
    padding: 20,
  },
  environmentInputList: {
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
  },
  environmentInputRow: {
    alignItems: "center",
    borderBottomColor: "var(--line-soft)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 14,
    gridTemplateColumns: "20px minmax(0, 1fr) auto",
    padding: 17,
  },
  environmentPresence: {
    fontFamily: mono,
    fontWeight: 900,
  },
  environmentReferenceList: {
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
  },
  environmentReferenceRow: {
    alignItems: "center",
    borderBottomColor: "var(--line-soft)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    fontFamily: mono,
    fontSize: "0.62rem",
    gap: 12,
    gridTemplateColumns: "1fr auto 1fr",
    padding: 17,
  },
  displayTitle: {
    fontFamily: display,
    fontStretch: "condensed",
    fontWeight: 900,
    letterSpacing: "-0.075em",
    margin: 0,
    textTransform: "uppercase",
  },
  heroTitle: {
    fontSize: {
      default: "clamp(5rem, 10vw, 10.5rem)",
      "@media (max-width: 760px)": "clamp(4.1rem, 22vw, 7rem)",
    },
    lineHeight: 0.7,
  },
  heroTitleAccent: {
    color: "var(--rey-accent)",
    display: "block",
    fontSize: "0.43em",
    letterSpacing: "-0.025em",
    marginTop: "0.46em",
  },
  eyebrow: {
    alignItems: "center",
    display: "flex",
    gap: 10,
    marginBlock: 0,
    marginBottom: 28,
    "::before": {
      backgroundColor: "var(--rey-accent)",
      content: '""',
      height: 3,
      width: 38,
    },
  },
  heroIntro: {
    fontSize: "clamp(1rem, 1.4vw, 1.24rem)",
    lineHeight: 1.55,
    marginBlock: 46,
    marginBottom: 34,
    maxWidth: 610,
  },
  heroLinks: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 22,
  },
  controlLabel: {
    fontFamily: mono,
    fontSize: "0.64rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  mechanicalLink: {
    borderBottomColor: "var(--rey-foreground)",
    borderBottomStyle: "solid",
    borderBottomWidth: 2,
    paddingBlock: 10,
    paddingBottom: 8,
    textDecoration: "none",
  },
  mechanicalArrow: {
    color: "var(--rey-accent)",
    display: "inline-block",
    marginLeft: 14,
    transform: { default: "none", ":hover": "translateX(5px)" },
    transitionDuration: {
      default: "140ms",
      "@media (prefers-reduced-motion: reduce)": "0.01ms",
    },
    transitionProperty: "transform",
    transitionTimingFunction: "ease",
  },
  portfolioMachine: {
    "--kinetic-surface-min-height": {
      default: "590px",
      "@media (max-width: 1050px)": "520px",
    },
    "--kinetic-surface-padding": {
      default: "clamp(34px, 5vw, 64px)",
      "@media (max-width: 760px)": "24px",
    },
    alignContent: "center",
    overflow: "hidden",
    "::before": {
      borderColor: "var(--line)",
      borderRadius: "50%",
      borderStyle: "solid",
      borderWidth: 1,
      content: '""',
      height: 12,
      left: 18,
      position: "absolute",
      top: 18,
      width: 12,
    },
    "::after": {
      borderColor: "var(--line)",
      borderRadius: "50%",
      borderStyle: "solid",
      borderWidth: 1,
      content: '""',
      height: 12,
      position: "absolute",
      right: 18,
      top: 18,
      width: 12,
    },
  },
  machineScale: {
    display: "flex",
    justifyContent: "space-between",
    left: "11%",
    position: "absolute",
    right: "11%",
    top: 54,
    "::before": {
      backgroundColor: "var(--line)",
      content: '""',
      height: 1,
      left: 0,
      position: "absolute",
      right: 0,
      top: 4,
    },
  },
  machineScaleTick: {
    backgroundColor: "var(--rey-background)",
    borderLeftColor: "var(--rey-foreground)",
    borderLeftStyle: "solid",
    borderLeftWidth: 1,
    height: 9,
    position: "relative",
  },
  machineReadout: {
    alignItems: "center",
    display: "grid",
    justifyItems: "center",
  },
  machineOutput: {
    color: "var(--rey-accent)",
    fontFamily: mono,
    fontSize: "clamp(5rem, 10vw, 9.5rem)",
    fontVariantNumeric: "tabular-nums",
    fontWeight: 900,
    letterSpacing: "-0.1em",
    lineHeight: 0.96,
    marginRight: "0.1em",
  },
  machineStatusGrid: {
    display: "grid",
    gap: 1,
    gridTemplateColumns: {
      default: "repeat(4, 1fr)",
      "@media (max-width: 760px)": "repeat(2, 1fr)",
    },
    marginTop: 42,
    width: "100%",
  },
  toneDanger: { color: "#b72d25" },
  toneWarning: { color: "#9a6411" },
  machinePlate: {
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    bottom: 24,
    display: "flex",
    gap: { default: 0, "@media (max-width: 760px)": 12 },
    justifyContent: "space-between",
    left: 24,
    paddingTop: 14,
    position: "absolute",
    right: 24,
  },
  muted: { color: "var(--muted)" },
  sectionSpacing: { marginTop: "clamp(68px, 9vw, 120px)" },
  sectionHeading: {
    alignItems: { default: "end", "@media (max-width: 760px)": "start" },
    borderBottomColor: "var(--rey-foreground)",
    borderBottomStyle: "solid",
    borderBottomWidth: 2,
    display: "grid",
    gap: 22,
    gridTemplateColumns: {
      default: "55px 1fr auto",
      "@media (max-width: 760px)": "34px 1fr",
    },
    marginBottom: 28,
    paddingBottom: 18,
  },
  sectionIndex: {
    color: "var(--rey-accent)",
    fontFamily: mono,
    fontSize: "1.3rem",
    fontWeight: 900,
  },
  sectionKicker: { marginBlock: 0, marginBottom: 5 },
  sectionTitle: {
    fontFamily: display,
    fontSize: "clamp(1.8rem, 3vw, 3rem)",
    fontStretch: "condensed",
    fontWeight: 900,
    letterSpacing: "-0.04em",
    margin: 0,
    textTransform: "uppercase",
  },
  sectionDetail: {
    color: "var(--muted)",
    gridColumn: { default: "auto", "@media (max-width: 760px)": 2 },
    textAlign: { default: "right", "@media (max-width: 760px)": "left" },
  },
  attentionTable: {
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
  },
  attentionGrid: {
    alignItems: { default: "center", "@media (max-width: 760px)": "start" },
    display: "grid",
    gap: 18,
    gridTemplateColumns: {
      default: "0.7fr 1.7fr 1.5fr 0.8fr 0.45fr",
      "@media (max-width: 760px)": "1fr auto",
    },
    paddingBlock: 15,
    paddingInline: 18,
  },
  attentionHeader: {
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    display: { default: "grid", "@media (max-width: 760px)": "none" },
    fontFamily: mono,
    fontSize: "0.56rem",
    letterSpacing: "0.1em",
  },
  attentionRow: {
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    minHeight: 66,
  },
  attentionText: {
    fontFamily: mono,
    fontSize: "0.67rem",
    letterSpacing: "0.05em",
  },
  attentionAction: { color: "var(--rey-accent)" },
  attentionSubject: {
    fontWeight: 700,
    gridColumn: { default: "auto", "@media (max-width: 760px)": "1 / -1" },
    overflowWrap: "anywhere",
  },
  attentionReason: {
    color: "var(--muted)",
    gridColumn: { default: "auto", "@media (max-width: 760px)": "1 / -1" },
    textTransform: "uppercase",
  },
  readinessExcluded: { opacity: 0.58 },
  progressTrack: {
    backgroundColor:
      "color-mix(in srgb, var(--rey-foreground) 10%, transparent)",
    height: 7,
    overflow: "hidden",
  },
  progressFill: {
    backgroundColor: "var(--rey-foreground)",
    display: "block",
    height: "100%",
  },
  accent: { color: "var(--rey-accent)" },
  systemPage: {
    alignContent: "center",
    display: "grid",
    justifyItems: "start",
    marginInline: "auto",
    maxWidth: 1200,
    minHeight: "calc(100vh - 105px)",
    padding: 60,
  },
  systemTitle: {
    fontSize: "clamp(4rem, 9vw, 8rem)",
    lineHeight: 0.8,
  },
  systemError: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    fontFamily: mono,
    fontSize: "0.7rem",
    marginTop: 38,
    maxWidth: "100%",
    overflow: "auto",
    padding: 22,
  },
  loader: {
    alignItems: "center",
    display: "flex",
    fontFamily: mono,
    fontSize: "0.7rem",
    gap: 18,
    letterSpacing: "0.08em",
  },
  loaderSpinner: {
    animationDuration: "900ms",
    animationIterationCount: "infinite",
    animationName: {
      default: calibrate,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    animationTimingFunction: "steps(4, end)",
    borderColor: "color-mix(in srgb, var(--rey-foreground) 16%, transparent)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderTopColor: "var(--rey-accent)",
    borderWidth: 7,
    height: 42,
    width: 42,
  },
  footer: {
    alignItems: {
      default: "center",
      "@media (max-width: 760px)": "flex-start",
    },
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    backdropFilter: "blur(14px)",
    backgroundColor:
      "color-mix(in srgb, var(--rey-background) 94%, transparent)",
    bottom: 0,
    display: "grid",
    gap: 18,
    gridTemplateColumns: "1fr auto 1fr",
    left: 0,
    minHeight: 54,
    paddingBlock: 12,
    paddingInline: 24,
    position: "fixed",
    right: 0,
    zIndex: 50,
  },
  footerButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "inherit",
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: mono,
    fontSize: "0.59rem",
    gap: 9,
    letterSpacing: "0.11em",
    padding: 0,
    textTransform: "uppercase",
  },
  footerMailbox: { justifySelf: "start" },
  mailboxCount: {
    alignItems: "center",
    borderColor: "var(--line)",
    borderRadius: 20,
    borderStyle: "solid",
    borderWidth: 1,
    color: "var(--muted)",
    display: "inline-flex",
    fontVariantNumeric: "tabular-nums",
    height: 19,
    justifyContent: "center",
    minWidth: 19,
    paddingInline: 5,
  },
  mailboxCountActive: {
    backgroundColor: "var(--rey-accent)",
    borderColor: "var(--rey-accent)",
    color: "var(--rey-background)",
  },
  communicationToggle: {
    color: "var(--muted)",
    fontSize: "0.86rem",
    justifySelf: "center",
    letterSpacing: "0.18em",
  },
  communicationsBackdrop: {
    backgroundColor:
      "color-mix(in srgb, var(--rey-foreground) 8%, transparent)",
    bottom: 54,
    left: 0,
    opacity: 0,
    pointerEvents: "none",
    position: "fixed",
    right: 0,
    top: 0,
    transitionDuration: {
      default: "180ms",
      "@media (prefers-reduced-motion: reduce)": "0.01ms",
    },
    transitionProperty: "opacity",
    zIndex: 48,
  },
  communicationsBackdropOpen: {
    opacity: 1,
    pointerEvents: "auto",
  },
  communicationsPanel: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--rey-foreground)",
    borderStyle: "solid",
    borderWidth: 1,
    bottom: 54,
    boxShadow:
      "0 -20px 60px color-mix(in srgb, var(--rey-foreground) 18%, transparent)",
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(240px, 0.32fr) minmax(0, 1fr)",
      "@media (max-width: 760px)": "1fr",
    },
    left: 0,
    maxHeight: "min(68vh, 640px)",
    opacity: 0,
    overflow: "hidden",
    pointerEvents: "none",
    position: "fixed",
    right: 0,
    transform: "translateY(calc(100% + 54px))",
    transitionDuration: {
      default: "180ms",
      "@media (prefers-reduced-motion: reduce)": "0.01ms",
    },
    transitionProperty: "transform, opacity",
    transitionTimingFunction: "cubic-bezier(0.2, 0.8, 0.2, 1)",
    zIndex: 49,
  },
  communicationsPanelOpen: {
    opacity: 1,
    pointerEvents: "auto",
    transform: "translateY(0)",
  },
  communicationsHeader: {
    alignContent: "space-between",
    borderBottomColor: {
      default: "transparent",
      "@media (max-width: 760px)": "var(--line)",
    },
    borderBottomStyle: "solid",
    borderBottomWidth: { default: 0, "@media (max-width: 760px)": 1 },
    borderRightColor: "var(--line)",
    borderRightStyle: "solid",
    borderRightWidth: { default: 1, "@media (max-width: 760px)": 0 },
    display: "grid",
    gap: 36,
    padding: "clamp(22px, 3vw, 42px)",
  },
  communicationsCoordinate: { display: "grid", gap: 7 },
  communicationsBody: {
    minHeight: 180,
    overflowY: "auto",
    overscrollBehavior: "contain",
  },
  communicationMessage: {
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 8,
    paddingBlock: 18,
    paddingInline: "clamp(20px, 3vw, 38px)",
  },
  communicationAction: { color: "var(--rey-accent)" },
  communicationsQuiet: {
    alignContent: "center",
    display: "grid",
    gap: 8,
    minHeight: 240,
    padding: "clamp(22px, 4vw, 52px)",
  },
  conversationBody: {
    display: "grid",
    gridTemplateRows: "minmax(180px, 1fr) auto",
    minHeight: 360,
    overflow: "hidden",
  },
  conversationThread: {
    alignContent: "start",
    display: "grid",
    gap: 14,
    overflowY: "auto",
    overscrollBehavior: "contain",
    padding: "clamp(22px, 4vw, 48px)",
  },
  conversationBoundary: {
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 10,
    lineHeight: 1.55,
    maxWidth: 720,
    padding: "clamp(18px, 3vw, 30px)",
  },
  conversationMessage: {
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 8,
    lineHeight: 1.55,
    paddingBlock: 16,
  },
  conversationComposer: {
    alignItems: "end",
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "grid",
    gap: 10,
    gridTemplateColumns: "minmax(0, 1fr) auto",
    padding: "16px clamp(18px, 3vw, 30px)",
  },
  conversationLabel: { gridColumn: "1 / -1" },
  conversationInput: {
    backgroundColor: "transparent",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "var(--muted)",
    fontFamily: mono,
    lineHeight: 1.5,
    minHeight: 74,
    padding: 12,
    resize: "none",
  },
  conversationInputEnabled: {
    color: "var(--rey-foreground)",
  },
  conversationSend: {
    alignSelf: "stretch",
    backgroundColor: "transparent",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "var(--muted)",
    fontFamily: mono,
    minWidth: 94,
    opacity: 0.62,
  },
  conversationSendEnabled: {
    borderColor: "var(--rey-accent)",
    color: "var(--rey-accent)",
    cursor: "pointer",
    opacity: 1,
  },
  conversationBoundaryNote: { gridColumn: "1 / -1" },
  footerLink: {
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    color: "inherit",
    justifySelf: "end",
    textDecoration: "none",
  },
});
