import * as stylex from "@stylexjs/stylex";

const mono = 'var(--mono, "SFMono-Regular", Consolas, monospace)';
const display =
  'var(--display, "Arial Narrow", "Roboto Condensed", sans-serif)';

export const exploreStyles = stylex.create({
  explorePage: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    height: "100%",
    marginInline: "auto",
    maxWidth: 1840,
    minHeight: 0,
    overflow: "hidden",
    paddingBlock: "clamp(24px, 3vw, 48px)",
    paddingInline: {
      default: "clamp(16px, 2.5vw, 42px)",
      "@media (max-width: 760px)": 10,
    },
    width: "100%",
  },
  micro: {
    fontFamily: mono,
    fontSize: "0.59rem",
    letterSpacing: "0.11em",
    textTransform: "uppercase",
  },
  coordinateBoundary: {
    alignItems: "center",
    backgroundColor: "color-mix(in srgb, #b57417 13%, var(--surface))",
    borderColor: "#89540d",
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flexShrink: 0,
    flexWrap: "wrap",
    fontFamily: mono,
    fontSize: "0.62rem",
    gap: "8px 18px",
    marginBottom: 14,
    padding: "10px 14px",
  },
  canvasShell: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderRadius: "var(--rey-radius)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow:
      "0 18px 48px color-mix(in srgb, var(--rey-foreground) 12%, transparent)",
    display: "flex",
    flex: 1,
    flexDirection: "column",
    height: "auto",
    minHeight: 0,
    overflow: "hidden",
  },
  canvasShellFullscreen: {
    borderRadius: 0,
    borderWidth: 0,
    height: "100vh",
    flex: "none",
    maxHeight: "none",
    width: "100vw",
  },
  canvasToolbar: {
    alignItems: "center",
    backgroundColor:
      "color-mix(in srgb, var(--rey-background) 94%, transparent)",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexDirection: { default: "row", "@media (max-width: 760px)": "column" },
    gap: { default: 22, "@media (max-width: 760px)": 14 },
    justifyContent: "space-between",
    minHeight: 76,
    paddingBlock: 12,
    paddingInline: 16,
    position: "relative",
    zIndex: 8,
  },
  lensReadout: {
    display: "grid",
    gap: 3,
    minWidth: 0,
  },
  canvasControls: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 7,
  },
  zoomReadout: {
    minWidth: 42,
    textAlign: "right",
  },
  controlButton: {
    fontFamily: mono,
    fontSize: "1rem",
    fontWeight: 900,
    minHeight: 38,
    minWidth: 40,
    paddingBlock: 7,
    paddingInline: 11,
  },
  textControlButton: {
    fontFamily: mono,
    fontSize: "0.56rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    minHeight: 38,
    paddingBlock: 7,
    paddingInline: 12,
  },
  canvasViewport: {
    backgroundColor: "var(--rey-background)",
    backgroundImage:
      "linear-gradient(90deg, var(--line-soft) 1px, transparent 1px), linear-gradient(var(--line-soft) 1px, transparent 1px)",
    backgroundPosition: "center center",
    backgroundSize: "32px 32px",
    cursor: "grab",
    flex: 1,
    minHeight: 0,
    outlineColor: {
      default: "transparent",
      ":focus-visible": "var(--rey-accent)",
    },
    outlineOffset: -3,
    outlineStyle: "solid",
    outlineWidth: {
      default: 0,
      ":focus-visible": 3,
    },
    overflow: "hidden",
    position: "relative",
    touchAction: "none",
    userSelect: "none",
  },
  terrainViewport: {
    backgroundColor: "color-mix(in srgb, #d9dccd 32%, var(--rey-background))",
    backgroundImage:
      "radial-gradient(circle at 16% 22%, color-mix(in srgb, #8fa77b 12%, transparent), transparent 31%), radial-gradient(circle at 76% 68%, color-mix(in srgb, #b79b6c 10%, transparent), transparent 34%)",
  },
  canvasViewportDragging: { cursor: "grabbing" },
  scene: {
    left: "50%",
    position: "absolute",
    top: "50%",
    transformOrigin: "center center",
    transitionDuration: {
      default: "220ms",
      "@media (prefers-reduced-motion: reduce)": "0.01ms",
    },
    transitionProperty: "transform",
    transitionTimingFunction: "cubic-bezier(.2,.8,.2,1)",
  },
  sceneDragging: { transitionDuration: "0ms" },
  projection: {
    height: "100%",
    position: "relative",
    width: "100%",
  },
  terrainProjection: {
    backgroundColor: "color-mix(in srgb, #eef0e3 25%, transparent)",
  },
  region: {
    alignContent: "start",
    backgroundColor: "color-mix(in srgb, var(--surface) 54%, transparent)",
    borderRadius: 18,
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    fontFamily: mono,
    fontSize: "0.62rem",
    gap: 4,
    gridAutoRows: "min-content",
    letterSpacing: "0.08em",
    padding: 16,
    position: "absolute",
    textTransform: "uppercase",
    zIndex: 0,
  },
  mapBoundary: {
    backgroundColor: "color-mix(in srgb, #89a76f 5%, transparent)",
    borderRadius: 46,
    borderStyle: "dashed",
    borderWidth: 1.5,
    color: "color-mix(in srgb, var(--rey-foreground) 75%, transparent)",
    pointerEvents: "none",
  },
  mapZone: {
    borderRadius: 28,
    fontSize: "0.5rem",
    opacity: 0.72,
    pointerEvents: "none",
  },
  regionNeutral: { borderColor: "var(--line)" },
  regionAccent: {
    borderColor: "color-mix(in srgb, var(--rey-accent) 70%, transparent)",
  },
  regionAttention: {
    borderColor: "color-mix(in srgb, #b57417 70%, transparent)",
  },
  regionHealthy: {
    borderColor: "color-mix(in srgb, #237047 70%, transparent)",
  },
  regionUnknown: {
    backgroundColor: "color-mix(in srgb, var(--muted) 5%, transparent)",
    borderColor: "color-mix(in srgb, var(--muted) 70%, transparent)",
    borderStyle: "dashed",
  },
  regionOmitted: {
    backgroundColor: "color-mix(in srgb, #8a5a19 8%, transparent)",
    borderColor: "#8a5a19",
    borderStyle: "dashed",
  },
  regionStale: {
    backgroundColor: "color-mix(in srgb, #8255a6 8%, transparent)",
    borderColor: "#8255a6",
  },
  regionUnsupported: {
    backgroundColor: "color-mix(in srgb, #686868 8%, transparent)",
    borderColor: "#686868",
    borderStyle: "dotted",
  },
  regionFrontier: {
    backgroundColor: "color-mix(in srgb, var(--rey-accent) 7%, transparent)",
    borderColor: "var(--rey-accent)",
    borderStyle: "dashed",
  },
  reliefLayer: {
    height: "100%",
    inset: 0,
    overflow: "visible",
    pointerEvents: "none",
    position: "absolute",
    width: "100%",
    zIndex: 1,
  },
  reliefContour: {
    fill: "none",
    opacity: 0.62,
    stroke: "color-mix(in srgb, #566c49 72%, var(--rey-foreground))",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    strokeWidth: 1.15,
    vectorEffect: "non-scaling-stroke",
  },
  reliefContourLow: {
    opacity: 0.36,
    strokeDasharray: "3 3",
  },
  reliefContourPeak: {
    opacity: 0.88,
    stroke: "color-mix(in srgb, #2f4f36 84%, var(--rey-foreground))",
    strokeWidth: 1.55,
  },
  edgeLayer: {
    height: "100%",
    inset: 0,
    overflow: "visible",
    pointerEvents: "none",
    position: "absolute",
    width: "100%",
    zIndex: 1,
  },
  edgeGroup: {
    fill: "var(--muted)",
    fontFamily: mono,
    fontSize: 9,
    letterSpacing: "0.08em",
  },
  edge: {
    stroke: "color-mix(in srgb, var(--rey-foreground) 38%, transparent)",
    strokeWidth: 1.5,
    vectorEffect: "non-scaling-stroke",
  },
  edgeDirects: {
    stroke: "var(--rey-accent)",
    strokeWidth: 2.4,
  },
  edgeContains: { strokeDasharray: "6 5" },
  edgeLabel: {
    paintOrder: "stroke",
    stroke: "var(--rey-background)",
    strokeWidth: 5,
    vectorEffect: "non-scaling-stroke",
  },
  pointOfInterest: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--rey-foreground)",
    cursor: "pointer",
    display: "flex",
    font: "inherit",
    gap: 9,
    padding: 0,
    position: "absolute",
    textAlign: "left",
    transform: {
      default: "translate(-50%, -50%) scale(var(--rey-terrain-counter-scale))",
      ":hover":
        "translate(-50%, calc(-50% - 3px)) scale(var(--rey-terrain-counter-scale))",
    },
    transformOrigin: "center center",
    transitionDuration: {
      default: "140ms",
      "@media (prefers-reduced-motion: reduce)": "0.01ms",
    },
    transitionProperty: "transform",
    zIndex: 4,
    ":focus-visible": {
      outlineColor: "var(--rey-accent)",
      outlineOffset: 5,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  pointMarker: {
    backgroundColor: "var(--surface-strong)",
    borderColor: "#315a3e",
    borderRadius: "50% 50% 50% 0",
    borderStyle: "solid",
    borderWidth: 3,
    boxShadow:
      "0 3px 0 color-mix(in srgb, var(--rey-foreground) 18%, transparent), 0 7px 15px color-mix(in srgb, var(--rey-foreground) 18%, transparent)",
    display: "block",
    flex: "0 0 auto",
    height: 18,
    position: "relative",
    transform: "rotate(-45deg)",
    width: 18,
    "::after": {
      backgroundColor: "#315a3e",
      borderRadius: "50%",
      content: '\"\"',
      height: 5,
      left: 4,
      position: "absolute",
      top: 4,
      width: 5,
    },
  },
  prominentPoint: {
    zIndex: 5,
  },
  frontierPoint: {
    opacity: 0.88,
  },
  frontierMarker: {
    borderColor: "#9a681d",
    borderRadius: 3,
    transform: "rotate(45deg)",
    "::after": { backgroundColor: "#9a681d" },
  },
  pointFamily: {
    color: "var(--muted)",
    fontSize: "0.45rem",
    fontStyle: "normal",
    letterSpacing: "0.1em",
  },
  pointName: {
    fontFamily: display,
    fontSize: "0.76rem",
    fontWeight: 900,
    letterSpacing: "-0.01em",
    lineHeight: 1,
    textTransform: "uppercase",
  },
  pointDetail: {
    color: "var(--muted)",
    fontSize: "0.44rem",
    fontStyle: "normal",
    maxWidth: 195,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  pointLabel: {
    backgroundColor:
      "color-mix(in srgb, var(--rey-background) 88%, transparent)",
    borderColor: "color-mix(in srgb, var(--line) 78%, transparent)",
    borderRadius: 4,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 4px 12px color-mix(in srgb, black 10%, transparent)",
    display: "grid",
    fontFamily: mono,
    gap: 2,
    maxWidth: 210,
    paddingBlock: 5,
    paddingInline: 7,
    whiteSpace: "nowrap",
  },
  topologyObject: {
    backgroundColor: "var(--surface-strong)",
    borderRadius: "var(--rey-radius)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: {
      default:
        "0 8px 0 color-mix(in srgb, var(--rey-foreground) 10%, transparent), 0 14px 24px color-mix(in srgb, var(--rey-foreground) 12%, transparent)",
      ":hover":
        "0 12px 0 color-mix(in srgb, var(--rey-foreground) 12%, transparent), 0 19px 31px color-mix(in srgb, var(--rey-foreground) 16%, transparent)",
      ":active": "inset 0 3px 8px color-mix(in srgb, black 15%, transparent)",
    },
    color: "var(--rey-foreground)",
    cursor: "pointer",
    display: "grid",
    font: "inherit",
    gap: 8,
    minHeight: 126,
    padding: 17,
    position: "absolute",
    textAlign: "left",
    textDecoration: "none",
    transform: {
      default: "translate(-50%, -50%)",
      ":hover": "translate(-50%, calc(-50% - 4px))",
      ":active": "translate(-50%, calc(-50% + 2px))",
    },
    transitionDuration: {
      default: "140ms",
      "@media (prefers-reduced-motion: reduce)": "0.01ms",
    },
    transitionProperty: "transform, box-shadow, border-color",
    transitionTimingFunction: "ease",
    zIndex: 3,
    ":focus-visible": {
      outlineColor: "var(--rey-accent)",
      outlineOffset: 4,
      outlineStyle: "solid",
      outlineWidth: 3,
    },
  },
  objectNeutral: { borderColor: "var(--line)" },
  objectAccent: {
    borderColor: "var(--rey-accent)",
    borderTopWidth: 5,
  },
  objectHealthy: {
    borderColor: "#237047",
    borderTopWidth: 5,
  },
  objectAttention: {
    borderColor: "#b57417",
    borderTopWidth: 5,
  },
  objectBlocked: {
    borderColor: "#a3302a",
    borderTopWidth: 5,
  },
  objectUnknown: {
    borderColor: "var(--muted)",
    borderStyle: "dashed",
    borderTopWidth: 5,
  },
  objectOmitted: {
    borderColor: "#8a5a19",
    borderStyle: "dashed",
    borderTopWidth: 5,
  },
  objectStale: {
    borderColor: "#8255a6",
    borderTopWidth: 5,
  },
  objectUnsupported: {
    borderColor: "#686868",
    borderStyle: "dotted",
    borderTopWidth: 5,
  },
  objectFrontier: {
    borderColor: "var(--rey-accent)",
    borderStyle: "dashed",
    borderTopWidth: 5,
  },
  objectFamily: {
    color: "var(--muted)",
    fontFamily: mono,
    fontSize: "0.54rem",
    letterSpacing: "0.1em",
  },
  objectLabel: {
    fontFamily: display,
    fontSize: "1.18rem",
    fontWeight: 900,
    letterSpacing: "-0.025em",
    lineHeight: 1,
    overflowWrap: "anywhere",
    textTransform: "uppercase",
  },
  objectDetail: {
    color: "var(--muted)",
    fontFamily: mono,
    fontSize: "0.54rem",
    lineHeight: 1.35,
    overflowWrap: "anywhere",
    textTransform: "uppercase",
  },
  objectAction: {
    alignSelf: "end",
    color: "var(--rey-accent)",
    fontFamily: mono,
    fontSize: "0.5rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    marginTop: 4,
    textTransform: "uppercase",
  },
  canvasCoordinates: {
    bottom: 14,
    color: "var(--muted)",
    display: "grid",
    fontFamily: mono,
    fontSize: "0.52rem",
    gap: 4,
    left: 16,
    letterSpacing: "0.08em",
    pointerEvents: "none",
    position: "absolute",
    zIndex: 5,
  },
  lensLegend: {
    alignItems: "center",
    backgroundColor:
      "color-mix(in srgb, var(--rey-background) 88%, transparent)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    display: { default: "flex", "@media (max-width: 760px)": "none" },
    gap: 8,
    paddingBlock: 8,
    paddingInline: 12,
    pointerEvents: "none",
    position: "absolute",
    right: 14,
    top: 14,
    zIndex: 5,
  },
  lensStep: {
    alignItems: "center",
    color: "var(--muted)",
    display: "flex",
    fontFamily: mono,
    fontSize: "0.48rem",
    gap: 6,
    letterSpacing: "0.07em",
    "::before": {
      borderColor: "var(--muted)",
      borderRadius: "50%",
      borderStyle: "solid",
      borderWidth: 1,
      content: '""',
      height: 6,
      width: 6,
    },
  },
  lensStepActive: {
    color: "var(--rey-foreground)",
    fontWeight: 800,
    "::before": {
      backgroundColor: "var(--rey-accent)",
      borderColor: "var(--rey-accent)",
    },
  },
  legendLine: { backgroundColor: "var(--line)", height: 1, width: 18 },
  canvasFooter: {
    alignItems: "center",
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    flexDirection: { default: "row", "@media (max-width: 760px)": "column" },
    fontFamily: mono,
    fontSize: "0.5rem",
    gap: 8,
    justifyContent: "space-between",
    letterSpacing: "0.07em",
    minHeight: 34,
    paddingBlock: 8,
    paddingInline: 14,
    textTransform: "uppercase",
  },
  coordinateUri: {
    color: "var(--muted)",
    maxWidth: "min(48vw, 680px)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
});
