import * as stylex from "@stylexjs/stylex";

const mono = 'var(--mono, "SFMono-Regular", Consolas, monospace)';
const display =
  'var(--display, "Arial Narrow", "Roboto Condensed", sans-serif)';

export const exploreStyles = stylex.create({
  explorePage: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    height: "100%",
    marginInline: "auto",
    maxWidth: 1840,
    minHeight: 0,
    overflow: "hidden",
    paddingBlock: "clamp(24px, 3vw, 48px)",
    paddingInline: {
      default: "clamp(16px, 2.5vw, 42px)",
      "@media (max-width: 760px)": 10,
    },
    width: "100%",
  },
  exploreHeading: {
    alignItems: "end",
    display: "grid",
    gap: 28,
    gridTemplateColumns: {
      default: "minmax(0, 1.35fr) minmax(320px, 0.65fr)",
      "@media (max-width: 900px)": "1fr",
    },
    marginBottom: {
      default: 28,
      "@media (max-height: 800px)": 14,
    },
    flexShrink: 0,
  },
  micro: {
    fontFamily: mono,
    fontSize: "0.59rem",
    letterSpacing: "0.11em",
    textTransform: "uppercase",
  },
  eyebrow: {
    alignItems: "center",
    display: "flex",
    gap: 10,
    marginBlock: 0,
    marginBottom: 12,
    "::before": {
      backgroundColor: "var(--rey-accent)",
      content: '""',
      height: 3,
      width: 38,
    },
  },
  exploreTitle: {
    fontFamily: display,
    fontSize: {
      default: "clamp(2.7rem, 6vw, 6rem)",
      "@media (max-height: 800px)": "clamp(2.2rem, 4vw, 4.3rem)",
    },
    fontStretch: "condensed",
    fontWeight: 900,
    letterSpacing: "-0.065em",
    lineHeight: 0.86,
    margin: 0,
    textTransform: "uppercase",
  },
  exploreIntroduction: {
    color: "var(--muted)",
    fontSize: "0.9rem",
    lineHeight: 1.55,
    margin: 0,
    maxWidth: 570,
    display: {
      default: "block",
      "@media (max-height: 680px)": "none",
    },
  },
  coordinateBoundary: {
    alignItems: "center",
    backgroundColor: "color-mix(in srgb, #b57417 13%, var(--surface))",
    borderColor: "#89540d",
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flexShrink: 0,
    flexWrap: "wrap",
    fontFamily: mono,
    fontSize: "0.62rem",
    gap: "8px 18px",
    marginBottom: 14,
    padding: "10px 14px",
  },
  canvasShell: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderRadius: "var(--rey-radius)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow:
      "0 18px 48px color-mix(in srgb, var(--rey-foreground) 12%, transparent)",
    display: "flex",
    flex: 1,
    flexDirection: "column",
    height: "auto",
    minHeight: 0,
    overflow: "hidden",
  },
  canvasShellFullscreen: {
    borderRadius: 0,
    borderWidth: 0,
    height: "100vh",
    flex: "none",
    maxHeight: "none",
    width: "100vw",
  },
  canvasToolbar: {
    alignItems: "center",
    backgroundColor:
      "color-mix(in srgb, var(--rey-background) 94%, transparent)",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexDirection: { default: "row", "@media (max-width: 760px)": "column" },
    gap: { default: 22, "@media (max-width: 760px)": 14 },
    justifyContent: "space-between",
    minHeight: 76,
    paddingBlock: 12,
    paddingInline: 16,
    position: "relative",
    zIndex: 8,
  },
  lensReadout: {
    display: "grid",
    gap: 3,
    minWidth: 0,
  },
  canvasControls: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 7,
  },
  zoomReadout: {
    minWidth: 42,
    textAlign: "right",
  },
  controlButton: {
    fontFamily: mono,
    fontSize: "1rem",
    fontWeight: 900,
    minHeight: 38,
    minWidth: 40,
    paddingBlock: 7,
    paddingInline: 11,
  },
  textControlButton: {
    fontFamily: mono,
    fontSize: "0.56rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    minHeight: 38,
    paddingBlock: 7,
    paddingInline: 12,
  },
  canvasViewport: {
    backgroundColor: "var(--rey-background)",
    backgroundImage:
      "linear-gradient(90deg, var(--line-soft) 1px, transparent 1px), linear-gradient(var(--line-soft) 1px, transparent 1px)",
    backgroundPosition: "center center",
    backgroundSize: "32px 32px",
    cursor: "grab",
    flex: 1,
    minHeight: 0,
    outlineColor: {
      default: "transparent",
      ":focus-visible": "var(--rey-accent)",
    },
    outlineOffset: -3,
    outlineStyle: "solid",
    outlineWidth: {
      default: 0,
      ":focus-visible": 3,
    },
    overflow: "hidden",
    position: "relative",
    touchAction: "none",
    userSelect: "none",
  },
  canvasViewportDragging: { cursor: "grabbing" },
  scene: {
    left: "50%",
    position: "absolute",
    top: "50%",
    transformOrigin: "center center",
    transitionDuration: {
      default: "220ms",
      "@media (prefers-reduced-motion: reduce)": "0.01ms",
    },
    transitionProperty: "transform",
    transitionTimingFunction: "cubic-bezier(.2,.8,.2,1)",
  },
  sceneDragging: { transitionDuration: "0ms" },
  projection: {
    height: "100%",
    position: "relative",
    width: "100%",
  },
  region: {
    backgroundColor: "color-mix(in srgb, var(--surface) 54%, transparent)",
    borderRadius: 18,
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    fontFamily: mono,
    fontSize: "0.62rem",
    gap: 4,
    letterSpacing: "0.08em",
    padding: 16,
    position: "absolute",
    textTransform: "uppercase",
  },
  regionNeutral: { borderColor: "var(--line)" },
  regionAccent: {
    borderColor: "color-mix(in srgb, var(--rey-accent) 70%, transparent)",
  },
  regionAttention: {
    borderColor: "color-mix(in srgb, #b57417 70%, transparent)",
  },
  regionHealthy: {
    borderColor: "color-mix(in srgb, #237047 70%, transparent)",
  },
  edgeLayer: {
    height: "100%",
    inset: 0,
    overflow: "visible",
    pointerEvents: "none",
    position: "absolute",
    width: "100%",
    zIndex: 1,
  },
  edgeGroup: {
    fill: "var(--muted)",
    fontFamily: mono,
    fontSize: 9,
    letterSpacing: "0.08em",
  },
  edge: {
    markerEnd: "url(#topology-arrow)",
    stroke: "color-mix(in srgb, var(--rey-foreground) 38%, transparent)",
    strokeWidth: 1.5,
  },
  edgeDirects: {
    stroke: "var(--rey-accent)",
    strokeWidth: 2.4,
  },
  edgeContains: { strokeDasharray: "6 5" },
  edgeLabel: {
    paintOrder: "stroke",
    stroke: "var(--rey-background)",
    strokeWidth: 5,
  },
  topologyObject: {
    backgroundColor: "var(--surface-strong)",
    borderRadius: "var(--rey-radius)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: {
      default:
        "0 8px 0 color-mix(in srgb, var(--rey-foreground) 10%, transparent), 0 14px 24px color-mix(in srgb, var(--rey-foreground) 12%, transparent)",
      ":hover":
        "0 12px 0 color-mix(in srgb, var(--rey-foreground) 12%, transparent), 0 19px 31px color-mix(in srgb, var(--rey-foreground) 16%, transparent)",
      ":active": "inset 0 3px 8px color-mix(in srgb, black 15%, transparent)",
    },
    color: "var(--rey-foreground)",
    cursor: "pointer",
    display: "grid",
    font: "inherit",
    gap: 8,
    minHeight: 126,
    padding: 17,
    position: "absolute",
    textAlign: "left",
    textDecoration: "none",
    transform: {
      default: "translate(-50%, -50%)",
      ":hover": "translate(-50%, calc(-50% - 4px))",
      ":active": "translate(-50%, calc(-50% + 2px))",
    },
    transitionDuration: {
      default: "140ms",
      "@media (prefers-reduced-motion: reduce)": "0.01ms",
    },
    transitionProperty: "transform, box-shadow, border-color",
    transitionTimingFunction: "ease",
    zIndex: 3,
    ":focus-visible": {
      outlineColor: "var(--rey-accent)",
      outlineOffset: 4,
      outlineStyle: "solid",
      outlineWidth: 3,
    },
  },
  objectNeutral: { borderColor: "var(--line)" },
  objectAccent: {
    borderColor: "var(--rey-accent)",
    borderTopWidth: 5,
  },
  objectHealthy: {
    borderColor: "#237047",
    borderTopWidth: 5,
  },
  objectAttention: {
    borderColor: "#b57417",
    borderTopWidth: 5,
  },
  objectBlocked: {
    borderColor: "#a3302a",
    borderTopWidth: 5,
  },
  objectFamily: {
    color: "var(--muted)",
    fontFamily: mono,
    fontSize: "0.54rem",
    letterSpacing: "0.1em",
  },
  objectLabel: {
    fontFamily: display,
    fontSize: "1.18rem",
    fontWeight: 900,
    letterSpacing: "-0.025em",
    lineHeight: 1,
    overflowWrap: "anywhere",
    textTransform: "uppercase",
  },
  objectDetail: {
    color: "var(--muted)",
    fontFamily: mono,
    fontSize: "0.54rem",
    lineHeight: 1.35,
    overflowWrap: "anywhere",
    textTransform: "uppercase",
  },
  objectAction: {
    alignSelf: "end",
    color: "var(--rey-accent)",
    fontFamily: mono,
    fontSize: "0.5rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    marginTop: 4,
    textTransform: "uppercase",
  },
  canvasCoordinates: {
    bottom: 14,
    color: "var(--muted)",
    display: "grid",
    fontFamily: mono,
    fontSize: "0.52rem",
    gap: 4,
    left: 16,
    letterSpacing: "0.08em",
    pointerEvents: "none",
    position: "absolute",
    zIndex: 5,
  },
  lensLegend: {
    alignItems: "center",
    backgroundColor:
      "color-mix(in srgb, var(--rey-background) 88%, transparent)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    display: { default: "flex", "@media (max-width: 760px)": "none" },
    gap: 8,
    paddingBlock: 8,
    paddingInline: 12,
    pointerEvents: "none",
    position: "absolute",
    right: 14,
    top: 14,
    zIndex: 5,
  },
  lensStep: {
    alignItems: "center",
    color: "var(--muted)",
    display: "flex",
    fontFamily: mono,
    fontSize: "0.48rem",
    gap: 6,
    letterSpacing: "0.07em",
    "::before": {
      borderColor: "var(--muted)",
      borderRadius: "50%",
      borderStyle: "solid",
      borderWidth: 1,
      content: '""',
      height: 6,
      width: 6,
    },
  },
  lensStepActive: {
    color: "var(--rey-foreground)",
    fontWeight: 800,
    "::before": {
      backgroundColor: "var(--rey-accent)",
      borderColor: "var(--rey-accent)",
    },
  },
  legendLine: { backgroundColor: "var(--line)", height: 1, width: 18 },
  canvasFooter: {
    alignItems: "center",
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    flexDirection: { default: "row", "@media (max-width: 760px)": "column" },
    fontFamily: mono,
    fontSize: "0.5rem",
    gap: 8,
    justifyContent: "space-between",
    letterSpacing: "0.07em",
    minHeight: 34,
    paddingBlock: 8,
    paddingInline: 14,
    textTransform: "uppercase",
  },
  coordinateUri: {
    color: "var(--muted)",
    maxWidth: "min(48vw, 680px)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
});
