import * as stylex from "@stylexjs/stylex";

const mono = 'var(--mono, "SFMono-Regular", Consolas, monospace)';
const display =
  'var(--display, "Arial Narrow", "Roboto Condensed", sans-serif)';

export const feedStyles = stylex.create({
  page: {
    backgroundColor: "color-mix(in srgb, var(--rey-background) 97%, white)",
    display: "flex",
    flex: 1,
    minHeight: 0,
    overflowX: "auto",
    overflowY: "hidden",
    scrollbarColor: "var(--rey-foreground) transparent",
    scrollbarWidth: "thin",
    width: "100%",
  },
  lane: {
    backgroundColor: "color-mix(in srgb, var(--rey-background) 97%, white)",
    borderRightColor: "var(--line)",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    display: "flex",
    flexBasis: 380,
    flexDirection: "column",
    flexGrow: 1,
    flexShrink: 0,
    maxWidth: 560,
    minHeight: 0,
    minWidth: 340,
  },
  laneHeader: {
    alignItems: "center",
    backgroundColor: "color-mix(in srgb, var(--rey-background) 94%, white)",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    flexShrink: 0,
    gap: 12,
    gridTemplateColumns: "minmax(0, 1fr) auto",
    minHeight: 66,
    paddingBlock: 10,
    paddingInline: 14,
  },
  laneIdentity: {
    alignItems: "center",
    display: "flex",
    gap: 10,
    minWidth: 0,
  },
  laneIndex: {
    alignItems: "center",
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    display: "flex",
    flexShrink: 0,
    fontFamily: mono,
    fontSize: "0.58rem",
    height: 26,
    justifyContent: "center",
    width: 26,
  },
  laneTitle: {
    fontSize: "1.03rem",
    lineHeight: 1.05,
    marginBlock: 2,
  },
  laneMeta: {
    alignItems: "end",
    display: "grid",
    gap: 6,
    justifyItems: "end",
  },
  laneActions: { display: "flex", gap: 3 },
  iconButton: {
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--surface-strong)",
    },
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "inherit",
    cursor: { default: "pointer", ":disabled": "default" },
    fontFamily: mono,
    height: 24,
    opacity: { default: 1, ":disabled": 0.25 },
    width: 26,
  },
  tuneButton: {
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--rey-foreground)",
    },
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    color: { default: "inherit", ":hover": "var(--rey-background)" },
    cursor: "pointer",
    fontFamily: mono,
    fontSize: "0.56rem",
    height: 24,
    paddingInline: 8,
  },
  laneScroll: {
    alignContent: "start",
    display: "grid",
    minHeight: 0,
    overflowY: "auto",
    overscrollBehavior: "contain",
    scrollbarColor: "var(--rey-foreground) transparent",
    scrollbarWidth: "thin",
  },
  composer: {
    alignItems: "center",
    backgroundColor: "color-mix(in srgb, var(--rey-accent) 3%, var(--surface))",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "dashed",
    borderBottomWidth: 1,
    color: "inherit",
    display: "grid",
    gap: 10,
    gridTemplateColumns: "30px minmax(0, 1fr) auto",
    padding: 12,
    textDecoration: "none",
  },
  post: {
    backgroundColor: "color-mix(in srgb, var(--surface) 72%, transparent)",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    minWidth: 0,
  },
  briefing: {
    backgroundColor: "color-mix(in srgb, var(--rey-accent) 4%, var(--surface))",
    borderLeftColor: "var(--rey-accent)",
    borderLeftStyle: "solid",
    borderLeftWidth: 3,
  },
  boundaryPost: { color: "var(--muted)" },
  postHeader: {
    alignItems: "center",
    display: "grid",
    gap: 9,
    gridTemplateColumns: "30px minmax(0, 1fr) auto",
    paddingBlock: 12,
    paddingInline: 14,
  },
  avatar: {
    alignItems: "center",
    backgroundColor: "var(--rey-foreground)",
    borderRadius: "50%",
    color: "var(--rey-background)",
    display: "flex",
    flexShrink: 0,
    fontFamily: display,
    fontSize: "0.67rem",
    fontWeight: 900,
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  avatarHuman: {
    backgroundColor: "var(--rey-accent)",
    color: "var(--rey-foreground)",
  },
  avatarAgent: { backgroundColor: "#355b72" },
  avatarGit: { backgroundColor: "#293d31" },
  avatarEnvironment: { backgroundColor: "#72592e" },
  avatarFlow: { backgroundColor: "#315c49" },
  avatarBoundary: {
    backgroundColor: "transparent",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "var(--muted)",
  },
  postIdentity: { display: "grid", gap: 2, minWidth: 0 },
  stateChip: {
    backgroundColor: "var(--surface-strong)",
    paddingBlock: 4,
    paddingInline: 6,
    textAlign: "right",
  },
  postBody: { paddingBlock: 2, paddingBottom: 14, paddingInline: 14 },
  postTitle: { fontSize: "1.02rem", marginBlock: 0 },
  postLead: {
    color: "var(--muted)",
    fontSize: "0.86rem",
    lineHeight: 1.45,
    marginBottom: 0,
  },
  postFooter: {
    alignItems: "center",
    borderTopColor: "var(--line-soft)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    justifyContent: "space-between",
    paddingBlock: 9,
    paddingInline: 14,
  },
  postAction: {
    color: "inherit",
    fontFamily: mono,
    fontSize: "0.59rem",
    textDecoration: "underline",
    textUnderlineOffset: 3,
  },
  emptyPost: {
    alignItems: "start",
    backgroundColor: "transparent",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "dashed",
    borderBottomWidth: 1,
    display: "grid",
    gap: 10,
    gridTemplateColumns: "30px 1fr",
    padding: 16,
  },
  admissionBoundary: {
    backgroundColor: "var(--surface-strong)",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    color: "var(--muted)",
    display: "grid",
    gap: 4,
    paddingBlock: 10,
    paddingInline: 14,
  },
  admissionEvidence: {
    borderLeftColor: "var(--line)",
    borderLeftStyle: "solid",
    borderLeftWidth: 2,
    display: "grid",
    gap: 4,
    marginTop: 12,
    paddingLeft: 10,
  },
  briefingCounts: {
    display: "flex",
    gap: 14,
    marginTop: 12,
  },
  flowProgress: { display: "grid", gap: 8, marginTop: 14 },
  flowTrack: {
    backgroundColor: "var(--line)",
    display: "block",
    height: 4,
    overflow: "hidden",
  },
  flowFill: {
    backgroundColor: "var(--rey-foreground)",
    display: "block",
    height: "100%",
  },
  flowEvidence: {
    color: "var(--muted)",
    display: "grid",
    fontSize: "0.76rem",
    gap: 5,
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    marginTop: 12,
  },
  journalAttachment: {
    borderColor: "var(--line-soft)",
    borderStyle: "solid",
    borderWidth: 1,
    marginTop: 12,
  },
  attachmentLabel: {
    alignItems: "center",
    backgroundColor: "var(--surface-strong)",
    color: "inherit",
    cursor: "pointer",
    display: "flex",
    justifyContent: "space-between",
    listStyle: "none",
    paddingBlock: 8,
    paddingInline: 10,
  },
  blockPreviews: { display: "grid", gap: 1 },
  blockBoundary: { color: "var(--muted)", padding: 14 },
  prosePreview: { lineHeight: 1.5, padding: 14 },
  diffPreview: {
    backgroundColor: "color-mix(in srgb, var(--rey-background) 94%, black)",
    display: "grid",
    gap: 8,
    padding: 14,
  },
  diffDirection: {
    alignItems: "center",
    display: "grid",
    gap: 8,
    gridTemplateColumns: "1fr auto 1fr",
  },
  framePreview: { display: "grid", gap: 8, overflowX: "auto", padding: 12 },
  previewTable: {
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
  },
  previewRow: {
    borderBottomColor: "var(--line-soft)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gridAutoColumns: "minmax(90px, 1fr)",
    gridAutoFlow: "column",
    minWidth: "max-content",
  },
  previewHeader: {
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
  },
  previewCell: { paddingBlock: 7, paddingInline: 9 },
  queryPreview: { backgroundColor: "#1e2221", color: "#f0f0e9", padding: 14 },
  explorePreview: {
    color: "inherit",
    display: "grid",
    gap: 7,
    padding: 14,
    textDecoration: "none",
  },
  actionPreview: { display: "grid", gap: 7, padding: 14 },
  mapBinding: {
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    color: "inherit",
    display: "grid",
    gap: 6,
    overflowWrap: "anywhere",
    padding: 12,
    textDecoration: "none",
  },
  commitAttachment: {
    backgroundColor: "#1e2221",
    color: "#f0f0e9",
    display: "grid",
    gap: 1,
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
  },
  commitIdentity: { display: "grid", gap: 8, padding: 13 },
  commitParents: {
    borderLeftColor: "#555",
    borderLeftStyle: "solid",
    borderLeftWidth: 1,
    display: "grid",
    gap: 7,
    padding: 13,
  },
  commitLink: { color: "inherit", fontFamily: mono },
  parentLink: { color: "inherit", fontFamily: mono },
  environmentAttachment: {
    alignItems: "center",
    backgroundColor: "color-mix(in srgb, #72592e 7%, var(--rey-background))",
    display: "grid",
    gap: 10,
    gridTemplateColumns: "1fr auto 1fr",
    padding: 13,
  },
  attachmentCell: { display: "grid", gap: 6 },
  sourceRecords: { display: "grid", gap: 1, marginTop: 12 },
  sourceRecord: {
    backgroundColor: "var(--rey-background)",
    borderColor: "var(--line-soft)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 4,
    padding: 9,
  },
  omissions: {
    fontFamily: mono,
    fontSize: "0.59rem",
    lineHeight: 1.5,
    marginBottom: 0,
    paddingLeft: 18,
  },
  firehoseRail: {
    alignItems: "center",
    backgroundColor: {
      default: "var(--surface)",
      ":hover": "var(--rey-foreground)",
    },
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderRightColor: "var(--line)",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    borderTopWidth: 0,
    color: { default: "inherit", ":hover": "var(--rey-background)" },
    cursor: { default: "pointer", ":disabled": "default" },
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    fontFamily: mono,
    gap: 10,
    justifyContent: "center",
    opacity: { default: 1, ":disabled": 0.3 },
    width: 54,
    writingMode: "vertical-rl",
  },
  firehose: {
    backgroundColor: "var(--surface)",
    flexBasis: 420,
    maxWidth: 480,
    minWidth: 380,
  },
  firehoseHeader: {
    alignItems: "center",
    borderBottomColor: "var(--rey-foreground)",
    borderBottomStyle: "solid",
    borderBottomWidth: 2,
    display: "flex",
    justifyContent: "space-between",
    minHeight: 66,
    paddingBlock: 10,
    paddingInline: 16,
  },
  firehoseBody: {
    display: "grid",
    gap: 22,
    minHeight: 0,
    overflowY: "auto",
    padding: 18,
  },
  firehoseLead: { color: "var(--muted)", lineHeight: 1.5, marginBlock: 0 },
  recipeGroup: {
    borderWidth: 0,
    display: "grid",
    gap: 7,
    margin: 0,
    padding: 0,
  },
  recipe: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--surface-strong)",
    },
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "inherit",
    cursor: "pointer",
    display: "grid",
    gap: 8,
    gridTemplateColumns: "80px minmax(0, 1fr) auto",
    padding: 12,
    textAlign: "left",
  },
  recipeActive: {
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
  },
  filterGrid: {
    display: "grid",
    gap: 6,
    gridTemplateColumns: "repeat(2, 1fr)",
  },
  filterButton: {
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--surface-strong)",
    },
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "inherit",
    cursor: "pointer",
    fontFamily: mono,
    fontSize: "0.62rem",
    padding: 10,
  },
  filterButtonActive: {
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
  },
  firehosePreview: {
    backgroundColor: "var(--rey-background)",
    borderColor: "var(--line)",
    borderStyle: "dashed",
    borderWidth: 1,
    display: "grid",
    gap: 7,
    padding: 14,
  },
  firehoseActions: {
    alignItems: "center",
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    justifyContent: "space-between",
    padding: 12,
  },
  secondaryButton: {
    backgroundColor: "transparent",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "inherit",
    cursor: "pointer",
    fontFamily: mono,
    fontSize: "0.59rem",
    marginRight: 5,
    paddingBlock: 9,
    paddingInline: 11,
  },
  primaryButton: {
    backgroundColor: "var(--rey-foreground)",
    borderColor: "var(--rey-foreground)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "var(--rey-background)",
    cursor: "pointer",
    fontFamily: mono,
    fontSize: "0.59rem",
    paddingBlock: 9,
    paddingInline: 11,
  },
  dangerButton: {
    backgroundColor: "transparent",
    borderColor: "var(--rey-accent)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "var(--rey-accent)",
    cursor: "pointer",
    fontFamily: mono,
    fontSize: "0.59rem",
    paddingBlock: 9,
    paddingInline: 11,
  },
});
