import * as stylex from "@stylexjs/stylex";

const mono = 'var(--mono, "SFMono-Regular", Consolas, monospace)';

export const journalStyles = stylex.create({
  entries: { display: "grid", gap: 24, marginTop: 28 },
  entry: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
  },
  entryHeader: {
    alignItems: "start",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 18,
    gridTemplateColumns: {
      default: "74px minmax(0, 1fr) auto",
      "@media (max-width: 680px)": "58px minmax(0, 1fr)",
    },
    padding: "22px 24px",
  },
  entryOrdinal: {
    alignItems: "center",
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    display: "flex",
    fontFamily: mono,
    fontSize: "0.72rem",
    height: 52,
    justifyContent: "center",
  },
  entryIdentity: { display: "grid", gap: 6, minWidth: 0 },
  blockStack: { display: "grid", gap: 1, backgroundColor: "var(--line)" },
  block: {
    backgroundColor: "var(--surface)",
    minWidth: 0,
    padding: "24px 26px",
  },
  blockHeader: {
    alignItems: "center",
    color: "var(--muted)",
    display: "flex",
    gap: 16,
    justifyContent: "space-between",
    marginBottom: 18,
  },
  proseBlock: { backgroundColor: "var(--surface-strong)" },
  proseDocument: { lineHeight: 1.72, maxWidth: 900 },
  exploreBlock: { display: "grid", gap: 13 },
  coordinate: { overflowWrap: "anywhere" },
  exploreLink: {
    borderBottomColor: "currentColor",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    color: "inherit",
    fontFamily: mono,
    fontSize: "0.64rem",
    justifySelf: "start",
    paddingBottom: 5,
    textDecoration: "none",
  },
  queryBlock: { backgroundColor: "#171a1a", color: "#f1f0e8" },
  queryMeta: {
    display: "flex",
    flexWrap: "wrap",
    fontFamily: mono,
    fontSize: "0.65rem",
    gap: 18,
  },
  codeSurface: {
    backgroundColor: "#0c0e0e",
    borderColor: "#4b5050",
    borderStyle: "solid",
    borderWidth: 1,
    color: "#e7e5d8",
    fontFamily: mono,
    lineHeight: 1.6,
    marginBottom: 0,
    overflowX: "auto",
    padding: 20,
    whiteSpace: "pre-wrap",
  },
  frameMeta: { display: "flex", gap: 18, justifyContent: "space-between" },
  frameScroll: { overflowX: "auto" },
  frameTable: {
    borderCollapse: "collapse",
    fontFamily: mono,
    fontSize: "0.7rem",
    marginTop: 16,
    width: "100%",
  },
  diffBlock: {
    borderLeftColor: "#9a3c25",
    borderLeftStyle: "solid",
    borderLeftWidth: 5,
  },
  actionBlock: {
    borderLeftColor: "#237047",
    borderLeftStyle: "solid",
    borderLeftWidth: 5,
  },
  entryBinding: {
    alignItems: "center",
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    flexWrap: "wrap",
    gap: 20,
    justifyContent: "space-between",
    padding: "16px 24px",
  },
  composeButton: {
    appearance: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--surface)",
      ":disabled": "transparent",
    },
    borderColor: "var(--line)",
    borderStyle: "dashed",
    borderWidth: 1,
    color: { default: "var(--rey-foreground)", ":disabled": "var(--muted)" },
    cursor: { default: "pointer", ":disabled": "not-allowed" },
    display: "grid",
    fontFamily: "inherit",
    gap: 9,
    marginTop: 14,
    opacity: 1,
    padding: 48,
    textAlign: "center",
    width: "100%",
  },
  composer: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--rey-foreground)",
    borderStyle: "solid",
    borderWidth: 2,
    marginTop: 28,
  },
  composerHeader: {
    alignItems: "start",
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    display: "flex",
    justifyContent: "space-between",
    padding: "22px 26px",
  },
  composerMeta: {
    display: "grid",
    gap: 1,
    gridTemplateColumns: {
      default: "0.4fr 1fr",
      "@media (max-width: 700px)": "1fr",
    },
  },
  field: { display: "grid", gap: 10, padding: "22px 26px" },
  control: {
    backgroundColor: "var(--rey-background)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "var(--rey-foreground)",
    fontFamily: "inherit",
    fontSize: "0.9rem",
    lineHeight: 1.5,
    outline: { default: "none", ":focus": "2px solid var(--rey-foreground)" },
    outlineOffset: 2,
    padding: "11px 13px",
    width: "100%",
  },
  textControl: { minHeight: 120, resize: "vertical" },
  queryControl: {
    backgroundColor: "#0c0e0e",
    borderColor: "#4b5050",
    color: "#f1f0e8",
    fontFamily: mono,
  },
  editorCell: { display: "grid", gap: 12, padding: 26 },
  bindingCell: {
    backgroundColor: "var(--surface-strong)",
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "grid",
    gap: 10,
    overflowWrap: "anywhere",
    padding: 22,
  },
  queryComposer: {
    backgroundColor: "#171a1a",
    color: "#f1f0e8",
    display: "grid",
    gap: 1,
  },
  addCell: {
    backgroundColor: "transparent",
    borderColor: "var(--line)",
    borderStyle: "dashed",
    borderWidth: 1,
    cursor: "pointer",
    fontFamily: mono,
    margin: 22,
    padding: 22,
  },
  composerError: { color: "#9a3c25", margin: 0, padding: "0 26px 20px" },
  textButton: {
    appearance: "none",
    backgroundColor: "transparent",
    borderColor: "currentColor",
    borderStyle: "solid",
    borderWidth: 1,
    color: "inherit",
    cursor: "pointer",
    fontFamily: mono,
    fontSize: "0.64rem",
    padding: "10px 13px",
  },
  submitButton: {
    appearance: "none",
    backgroundColor: {
      default: "var(--rey-foreground)",
      ":disabled": "var(--line)",
    },
    borderWidth: 0,
    color: {
      default: "var(--rey-background)",
      ":disabled": "var(--muted)",
    },
    cursor: { default: "pointer", ":disabled": "wait" },
    fontFamily: mono,
    fontSize: "0.67rem",
    padding: "13px 16px",
  },
  composerFooter: {
    alignItems: "center",
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    gap: 20,
    justifyContent: "space-between",
    padding: "20px 26px",
  },
});
