import * as stylex from "@stylexjs/stylex";

const mono = 'var(--mono, "SFMono-Regular", Consolas, monospace)';
const display =
  'var(--display, "Arial Narrow", "Roboto Condensed", sans-serif)';

export const workloadsStyles = stylex.create({
  page: { paddingTop: "clamp(46px, 6vw, 88px)" },
  section: { marginTop: "clamp(74px, 9vw, 126px)" },
  firstSection: { marginTop: 0 },
  portfolioLink: {
    color: "inherit",
    display: "inline-block",
    fontFamily: mono,
    fontSize: "0.64rem",
    letterSpacing: "0.08em",
    marginBottom: 54,
    textDecoration: "none",
  },
  sectionHeading: {
    alignItems: "end",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 20,
    gridTemplateColumns: {
      default: "72px minmax(0, 1fr) auto",
      "@media (max-width: 700px)": "52px 1fr",
    },
    paddingBottom: 17,
  },
  sectionIndex: {
    fontFamily: display,
    fontSize: "2.8rem",
    fontWeight: 900,
    lineHeight: 0.8,
  },
  kicker: { marginBlock: 0, marginBottom: 5 },
  table: {
    "--kinetic-dense-table-cell-padding": "18px 20px",
    marginTop: 20,
  },
  row: {
    backgroundColor: {
      default: "var(--surface)",
      ":hover": "var(--surface-strong)",
    },
  },
  rowFailure: {
    backgroundColor: "color-mix(in srgb, #b72d25 7%, var(--surface))",
  },
  rowStale: {
    backgroundColor: "color-mix(in srgb, #b57417 8%, var(--surface))",
  },
  draftRow: {
    backgroundColor: "color-mix(in srgb, var(--rey-accent) 6%, var(--surface))",
  },
  identity: {
    alignItems: "start",
    display: "flex",
    gap: 14,
    minWidth: 0,
  },
  identityDetail: { display: "grid", gap: 6, minWidth: 0 },
  ordinal: {
    alignItems: "center",
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    display: "flex",
    flexShrink: 0,
    fontFamily: mono,
    fontSize: "0.64rem",
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  cellStack: { display: "grid", gap: 7, minWidth: 0 },
  outcomes: {
    display: "grid",
    gap: 5,
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
  },
  description: {
    color: "var(--muted)",
    lineHeight: 1.4,
    margin: 0,
  },
  secondary: { color: "var(--muted)", fontSize: "0.72rem" },
  breakable: { overflowWrap: "anywhere" },
  conformance: { display: "grid", gap: 7 },
  conformanceSummary: {
    alignItems: "center",
    display: "flex",
    gap: 12,
    justifyContent: "space-between",
  },
  progressTrack: {
    backgroundColor: "var(--line)",
    display: "block",
    height: 5,
    overflow: "hidden",
  },
  progressFill: {
    backgroundColor: "var(--rey-foreground)",
    display: "block",
    height: "100%",
  },
  progressFailure: { backgroundColor: "#b72d25" },
  progressStale: { backgroundColor: "#b57417" },
  metricTable: { "--kinetic-dense-table-cell-padding": "24px 20px" },
  metricValue: {
    fontFamily: display,
    fontSize: "clamp(1.8rem, 3vw, 3.2rem)",
    fontWeight: 900,
    lineHeight: 1,
  },
  location: {
    borderBottomColor: "currentColor",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    color: "inherit",
    display: "inline-block",
    fontFamily: mono,
    fontSize: "0.62rem",
    letterSpacing: "0.08em",
    paddingBottom: 6,
    textDecoration: "none",
  },
  evidenceSummary: {
    display: "grid",
    gap: 10,
    gridTemplateColumns: {
      default: "repeat(4, minmax(0, 1fr))",
      "@media (max-width: 800px)": "repeat(2, minmax(0, 1fr))",
    },
    marginTop: 20,
  },
  evidenceMetric: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 7,
    minWidth: 0,
    padding: 18,
  },
  evidenceList: { display: "grid", gap: 12, marginTop: 20 },
  evidenceCard: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 12,
    minWidth: 0,
    padding: "18px 20px",
  },
  evidenceCardHeader: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
    justifyContent: "space-between",
  },
  evidenceValues: {
    display: "grid",
    gap: 8,
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 700px)": "1fr",
    },
  },
  evidenceValue: {
    backgroundColor: "var(--background)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 7,
    margin: 0,
    minHeight: 72,
    overflowWrap: "anywhere",
    padding: 14,
    whiteSpace: "pre-wrap",
  },
  patch: {
    backgroundColor: "var(--background)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    fontFamily: mono,
    fontSize: "0.72rem",
    lineHeight: 1.6,
    margin: 0,
    overflowX: "auto",
    padding: 16,
    whiteSpace: "pre-wrap",
  },
  exactRows: {
    display: "grid",
    gap: 0,
    margin: 0,
    marginTop: 20,
  },
  exactRow: {
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 14,
    gridTemplateColumns: {
      default: "180px minmax(0, 1fr)",
      "@media (max-width: 700px)": "1fr",
    },
    paddingBlock: 12,
  },
  exactValue: {
    margin: 0,
    overflowWrap: "anywhere",
  },
  sourceLink: {
    color: "inherit",
    fontFamily: mono,
    overflowWrap: "anywhere",
    textDecorationLine: "underline",
    textUnderlineOffset: 4,
  },
  omission: { color: "#9a5b0f" },
  evidenceEmpty: {
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "var(--muted)",
    marginTop: 20,
    padding: 22,
  },
});
