[package]
name = "rey-environment"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
polars.workspace = true
rey-core = { path = "../rey-core" }
rey-dataframe = { path = "../rey-dataframe" }
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
