[package]
name = "rey-diff"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
csv.workspace = true
polars.workspace = true
rey-core = { path = "../rey-core" }
rey-dataframe = { path = "../rey-dataframe" }
rey-environment = { path = "../rey-environment" }
rey-mining = { path = "../rey-mining" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
