import * as stylex from "@stylexjs/stylex";

const mono = 'var(--mono, "SFMono-Regular", Consolas, monospace)';
const display =
  'var(--display, "Arial Narrow", "Roboto Condensed", sans-serif)';

export const agentsStyles = stylex.create({
  page: { paddingTop: "clamp(46px, 6vw, 88px)" },
  section: { marginTop: "clamp(74px, 9vw, 126px)" },
  firstSection: { marginTop: 0 },
  sectionHeading: {
    alignItems: "end",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 20,
    gridTemplateColumns: {
      default: "72px minmax(0, 1fr) auto",
      "@media (max-width: 700px)": "52px 1fr",
    },
    paddingBottom: 17,
  },
  sectionIndex: {
    fontFamily: display,
    fontSize: "2.8rem",
    fontWeight: 900,
    lineHeight: 0.8,
  },
  kicker: { marginBlock: 0, marginBottom: 5 },
  empty: {
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "var(--muted)",
    marginTop: 28,
    padding: 48,
    textAlign: "center",
  },
  table: {
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    marginTop: 20,
  },
  processSummary: {
    backgroundColor: "var(--line)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    gap: 1,
    gridTemplateColumns: {
      default: "repeat(4, minmax(0, 1fr))",
      "@media (max-width: 980px)": "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 560px)": "1fr",
    },
    marginTop: 28,
  },
  processCell: {
    backgroundColor: "var(--surface)",
    display: "grid",
    gap: 9,
    lineHeight: 1.4,
    minWidth: 0,
    padding: "20px",
  },
  topologyBoundary: {
    color: "var(--muted)",
    lineHeight: 1.6,
    marginTop: 14,
  },
  topologyHeader: {
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    display: {
      default: "grid",
      "@media (max-width: 980px)": "none",
    },
    gap: 18,
    gridTemplateColumns:
      "minmax(210px, 1fr) minmax(145px, 0.6fr) minmax(180px, 0.72fr) minmax(180px, 0.72fr) minmax(260px, 1.1fr)",
    padding: "12px 20px",
  },
  topologyRow: {
    alignItems: "center",
    backgroundColor: "var(--surface)",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 18,
    gridTemplateColumns: {
      default:
        "minmax(210px, 1fr) minmax(145px, 0.6fr) minmax(180px, 0.72fr) minmax(180px, 0.72fr) minmax(260px, 1.1fr)",
      "@media (max-width: 980px)": "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 560px)": "1fr",
    },
    minWidth: 0,
    padding: "clamp(20px, 3vw, 32px)",
  },
  opportunityBoundary: {
    backgroundColor: "var(--surface-strong)",
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    color: "var(--muted)",
    lineHeight: 1.5,
    padding: "14px 20px",
  },
  journalHeader: {
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    display: {
      default: "grid",
      "@media (max-width: 1120px)": "none",
    },
    gap: 18,
    gridTemplateColumns:
      "minmax(210px, 1fr) minmax(145px, 0.68fr) minmax(230px, 1.05fr) minmax(150px, 0.65fr) minmax(150px, 0.65fr) minmax(155px, 0.62fr)",
    padding: "12px 20px",
  },
  ledgerHeader: {
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    display: {
      default: "grid",
      "@media (max-width: 1120px)": "none",
    },
    gap: 18,
    gridTemplateColumns:
      "minmax(230px, 1.05fr) minmax(150px, 0.65fr) minmax(190px, 0.82fr) minmax(210px, 0.9fr) minmax(155px, 0.65fr) minmax(155px, 0.62fr)",
    padding: "12px 20px",
  },
  journalRow: {
    alignItems: "center",
    backgroundColor: {
      default: "var(--surface)",
      ":hover": "var(--surface-strong)",
    },
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 18,
    gridTemplateColumns: {
      default:
        "minmax(210px, 1fr) minmax(145px, 0.68fr) minmax(230px, 1.05fr) minmax(150px, 0.65fr) minmax(150px, 0.65fr) minmax(155px, 0.62fr)",
      "@media (max-width: 1120px)": "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 640px)": "1fr",
    },
    minWidth: 0,
    padding: "clamp(20px, 3vw, 32px)",
  },
  ledgerRow: {
    alignItems: "center",
    backgroundColor: {
      default: "var(--surface)",
      ":hover": "var(--surface-strong)",
    },
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 18,
    gridTemplateColumns: {
      default:
        "minmax(230px, 1.05fr) minmax(150px, 0.65fr) minmax(190px, 0.82fr) minmax(210px, 0.9fr) minmax(155px, 0.65fr) minmax(155px, 0.62fr)",
      "@media (max-width: 1120px)": "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 640px)": "1fr",
    },
    minWidth: 0,
    padding: "clamp(20px, 3vw, 32px)",
  },
  identity: {
    alignItems: "start",
    display: "flex",
    gap: 16,
    minWidth: 0,
  },
  identityDetail: { display: "grid", gap: 7, minWidth: 0 },
  identityDescription: {
    color: "var(--muted)",
    lineHeight: 1.4,
    margin: 0,
  },
  ordinal: {
    alignItems: "center",
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    display: "flex",
    flexShrink: 0,
    fontFamily: mono,
    fontSize: "0.66rem",
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  operation: { display: "grid", gap: 8 },
  reason: { display: "grid", gap: 8, lineHeight: 1.45 },
  reasonText: { margin: 0 },
  bounds: { display: "grid", gap: 8 },
  readiness: { display: "grid", gap: 8 },
  result: { display: "grid", gap: 7 },
  resultSummary: {
    alignItems: "center",
    display: "flex",
    gap: 12,
    justifyContent: "space-between",
  },
  resultTrack: {
    backgroundColor: "var(--line)",
    display: "block",
    height: 5,
    overflow: "hidden",
  },
  resultFill: {
    backgroundColor: "var(--rey-foreground)",
    display: "block",
    height: "100%",
  },
  resultMeta: { color: "var(--muted)" },
  artifacts: { display: "grid", gap: 8, lineHeight: 1.45 },
  systemRead: { display: "grid", gap: 8 },
  locate: {
    borderBottomColor: "currentColor",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    color: "inherit",
    fontFamily: mono,
    fontSize: "0.64rem",
    justifySelf: "start",
    letterSpacing: "0.08em",
    paddingBottom: 6,
    textDecoration: "none",
  },
  unlocated: { color: "var(--muted)" },
});
