import * as stylex from "@stylexjs/stylex";

const mono = 'var(--mono, "SFMono-Regular", Consolas, monospace)';
const display =
  'var(--display, "Arial Narrow", "Roboto Condensed", sans-serif)';

const beaconPulse = stylex.keyframes({
  "0%, 100%": { opacity: 0.3, transform: "scale(0.84)" },
  "50%": { opacity: 0.78, transform: "scale(1.12)" },
});

export const exploreStyles = stylex.create({
  explorePage: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    height: "100%",
    marginInline: "auto",
    maxWidth: 1840,
    minHeight: 0,
    overflow: "hidden",
    paddingBlock: "clamp(24px, 3vw, 48px)",
    paddingInline: {
      default: "clamp(16px, 2.5vw, 42px)",
      "@media (max-width: 760px)": 10,
    },
    width: "100%",
  },
  micro: {
    fontFamily: mono,
    fontSize: "0.59rem",
    letterSpacing: "0.11em",
    textTransform: "uppercase",
  },
  coordinateBoundary: {
    alignItems: "center",
    backgroundColor: "color-mix(in srgb, #b57417 13%, var(--surface))",
    borderColor: "#89540d",
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flexShrink: 0,
    flexWrap: "wrap",
    fontFamily: mono,
    fontSize: "0.62rem",
    gap: "8px 18px",
    marginBottom: 14,
    padding: "10px 14px",
  },
  canvasShell: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderRadius: "var(--rey-radius)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow:
      "0 18px 48px color-mix(in srgb, var(--rey-foreground) 12%, transparent)",
    display: "flex",
    flex: 1,
    flexDirection: "column",
    height: "auto",
    minHeight: 0,
    overflow: "hidden",
    position: "relative",
  },
  orientationCanvasShell: {
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: 0,
    boxShadow: "none",
  },
  canvasShellFullscreen: {
    borderRadius: 0,
    borderWidth: 0,
    height: "100vh",
    flex: "none",
    maxHeight: "none",
    width: "100vw",
  },
  canvasToolbar: {
    alignItems: "center",
    backgroundColor:
      "color-mix(in srgb, var(--rey-background) 94%, transparent)",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexDirection: { default: "row", "@media (max-width: 760px)": "column" },
    gap: { default: 22, "@media (max-width: 760px)": 14 },
    justifyContent: "space-between",
    minHeight: 76,
    paddingBlock: 12,
    paddingInline: 16,
    position: "relative",
    zIndex: 8,
  },
  orientationCanvasToolbar: {
    backgroundColor: "color-mix(in srgb, #e3e4de 88%, transparent)",
    borderBottomColor: "color-mix(in srgb, #6f827d 22%, transparent)",
  },
  lensReadout: {
    display: "grid",
    gap: 3,
    minWidth: 0,
  },
  canvasControls: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 7,
  },
  zoomReadout: {
    minWidth: 42,
    textAlign: "right",
  },
  controlButton: {
    fontFamily: mono,
    fontSize: "1rem",
    fontWeight: 900,
    minHeight: 38,
    minWidth: 40,
    paddingBlock: 7,
    paddingInline: 11,
  },
  textControlButton: {
    fontFamily: mono,
    fontSize: "0.56rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    minHeight: 38,
    paddingBlock: 7,
    paddingInline: 12,
  },
  canvasViewport: {
    backgroundColor: "var(--rey-background)",
    backgroundImage:
      "linear-gradient(90deg, var(--line-soft) 1px, transparent 1px), linear-gradient(var(--line-soft) 1px, transparent 1px)",
    backgroundPosition: "center center",
    backgroundSize: "32px 32px",
    cursor: "grab",
    flex: 1,
    minHeight: 0,
    outlineColor: {
      default: "transparent",
      ":focus-visible": "var(--rey-accent)",
    },
    outlineOffset: -3,
    outlineStyle: "solid",
    outlineWidth: {
      default: 0,
      ":focus-visible": 3,
    },
    overflow: "hidden",
    position: "relative",
    touchAction: "none",
    userSelect: "none",
  },
  terrainViewport: {
    backgroundColor: "color-mix(in srgb, #d9dccd 32%, var(--rey-background))",
    backgroundImage:
      "radial-gradient(circle at 16% 22%, color-mix(in srgb, #8fa77b 12%, transparent), transparent 31%), radial-gradient(circle at 76% 68%, color-mix(in srgb, #b79b6c 10%, transparent), transparent 34%)",
  },
  orientationViewport: {
    backgroundColor: "#e3e4de",
    backgroundImage:
      "radial-gradient(circle at 50% 46%, rgba(255, 250, 232, 0.86), rgba(230, 232, 223, 0.58) 32%, rgba(177, 194, 186, 0.22) 57%, transparent 76%), linear-gradient(135deg, rgba(45, 78, 72, 0.025) 25%, transparent 25%, transparent 75%, rgba(45, 78, 72, 0.025) 75%)",
    backgroundSize: "auto, 52px 52px",
  },
  canvasViewportDragging: { cursor: "grabbing" },
  scene: {
    left: "50%",
    position: "absolute",
    top: "50%",
    transformOrigin: "center center",
    transitionDuration: {
      default: "220ms",
      "@media (prefers-reduced-motion: reduce)": "0.01ms",
    },
    transitionProperty: "transform",
    transitionTimingFunction: "cubic-bezier(.2,.8,.2,1)",
  },
  sceneDragging: { transitionDuration: "0ms" },
  projection: {
    height: "100%",
    position: "relative",
    width: "100%",
  },
  terrainProjection: {
    backgroundColor: "color-mix(in srgb, #eef0e3 25%, transparent)",
  },
  countyProjection: {
    backgroundColor: "color-mix(in srgb, #d8e2d3 34%, transparent)",
    backgroundImage:
      "radial-gradient(ellipse at 34% 42%, color-mix(in srgb, #78946d 12%, transparent), transparent 34%), radial-gradient(ellipse at 68% 58%, color-mix(in srgb, #526f5c 10%, transparent), transparent 38%)",
  },
  acceleratedTerrainProjection: { backgroundColor: "transparent" },
  acceleratedTerrainCanvas: {
    height: "100%",
    inset: 0,
    opacity: 0,
    pointerEvents: "none",
    position: "absolute",
    transitionDuration: {
      default: "180ms",
      "@media (prefers-reduced-motion: reduce)": "0.01ms",
    },
    transitionProperty: "opacity",
    width: "100%",
    zIndex: 0,
  },
  acceleratedTerrainCanvasReady: { opacity: 1 },
  worldTerrainProjection: {
    backgroundColor: "transparent",
  },
  worldGeometryLayer: {
    height: "100%",
    inset: 0,
    overflow: "visible",
    pointerEvents: "none",
    position: "absolute",
    width: "100%",
    zIndex: 0,
  },
  countyFootprintLayer: {
    zIndex: 0,
  },
  countyFootprint: {
    fill: "color-mix(in srgb, #89a76f 11%, var(--rey-background))",
    stroke: "color-mix(in srgb, #47604d 58%, var(--rey-foreground))",
    strokeLinejoin: "round",
    strokeWidth: 2,
    vectorEffect: "non-scaling-stroke",
  },
  countyFootprintAccelerated: {
    fill: "transparent",
    opacity: 0.42,
    strokeWidth: 1.2,
  },
  countyFootprintSubordinate: {
    fill: "transparent",
    opacity: 0.1,
    strokeWidth: 0.7,
  },
  countyFeatureLayer: {
    pointerEvents: "auto",
    zIndex: 3,
  },
  countyFeature: {
    cursor: "pointer",
    outline: {
      default: "none",
      ":focus-visible": "2px solid var(--rey-accent)",
    },
  },
  countyFeatureAcceleratedGeometry: {
    fill: "transparent",
    opacity: 0,
    pointerEvents: "all",
    stroke: "transparent",
  },
  countyFeatureEnvelope: {
    fill: "color-mix(in srgb, #78946d 9%, transparent)",
    stroke: "color-mix(in srgb, #355b4c 44%, var(--rey-foreground))",
    strokeLinejoin: "round",
    strokeWidth: "calc(1.2px * var(--rey-terrain-counter-scale))",
    vectorEffect: "non-scaling-stroke",
  },
  countyFeatureLinear: {
    fill: "none",
    stroke: "color-mix(in srgb, #b67a2c 68%, var(--rey-foreground))",
    strokeWidth: "calc(1.8px * var(--rey-terrain-counter-scale))",
  },
  countyFeatureHydrology: {
    fill: "none",
    opacity: 0.68,
    stroke: "color-mix(in srgb, #72a6ae 80%, var(--rey-foreground))",
    strokeWidth: "calc(1.25px * var(--rey-terrain-counter-scale))",
  },
  countyFeatureHighway: {
    stroke: "#eee6d5",
    strokeWidth: "calc(2.2px * var(--rey-terrain-counter-scale))",
  },
  countyFeatureRoad: {
    stroke: "#d7d0c2",
    strokeWidth: "calc(1.15px * var(--rey-terrain-counter-scale))",
  },
  countyFeatureRailway: {
    stroke: "#5e5b56",
    strokeDasharray:
      "calc(5px * var(--rey-terrain-counter-scale)) calc(3px * var(--rey-terrain-counter-scale))",
    strokeWidth: "calc(1px * var(--rey-terrain-counter-scale))",
  },
  countyFeatureDistrict: {
    fill: "none",
    opacity: 0.42,
    stroke: "#726f66",
    strokeDasharray:
      "calc(2px * var(--rey-terrain-counter-scale)) calc(5px * var(--rey-terrain-counter-scale))",
    strokeWidth: "calc(0.75px * var(--rey-terrain-counter-scale))",
  },
  countyFeatureWaterArea: {
    fill: "color-mix(in srgb, #4f93a0 48%, transparent)",
    opacity: 0.74,
    stroke: "color-mix(in srgb, #356f7a 72%, var(--rey-foreground))",
    strokeWidth: "calc(1.15px * var(--rey-terrain-counter-scale))",
  },
  countyFeatureBoundary: {
    fill: "none",
    stroke: "color-mix(in srgb, #314941 64%, var(--rey-foreground))",
    strokeDasharray: "2 4",
    strokeWidth: "calc(1px * var(--rey-terrain-counter-scale))",
  },
  countyTerrainControl: {
    fill: "color-mix(in srgb, #7d7160 5%, transparent)",
    stroke: "color-mix(in srgb, #78684f 47%, var(--rey-foreground))",
    strokeDasharray: "4 5",
  },
  countyFeaturePoint: {
    fill: "#446c61",
    stroke: "#f0ead6",
    strokeWidth: 1.5,
    transform: "scale(var(--rey-terrain-counter-scale))",
    transformBox: "fill-box",
    transformOrigin: "center",
    vectorEffect: "non-scaling-stroke",
  },
  countyTerrainSampleHalo: {
    fill: "color-mix(in srgb, #446c61 12%, transparent)",
    stroke: "color-mix(in srgb, #446c61 54%, transparent)",
    strokeWidth: 1,
    vectorEffect: "non-scaling-stroke",
  },
  countyFeatureSelected: {
    filter:
      "drop-shadow(0 0 7px color-mix(in srgb, var(--rey-accent) 62%, transparent))",
  },
  countyFeatureLabel: {
    fill: "var(--rey-foreground)",
    fontFamily: mono,
    fontSize: "calc(9px * var(--rey-terrain-counter-scale))",
    fontWeight: 800,
    letterSpacing: "0.05em",
    paintOrder: "stroke",
    pointerEvents: "none",
    stroke: "color-mix(in srgb, var(--rey-background) 92%, transparent)",
    strokeWidth: "calc(3px * var(--rey-terrain-counter-scale))",
  },
  countyFeatureEvidenceLabel: {
    fill: "var(--rey-accent)",
    fontFamily: mono,
    fontSize: 7,
    fontWeight: 850,
    letterSpacing: "0.08em",
    paintOrder: "stroke",
    pointerEvents: "none",
    stroke: "color-mix(in srgb, var(--rey-background) 94%, transparent)",
    strokeWidth: 3,
  },
  worldGraticule: {
    fill: "none",
    opacity: 0.22,
    stroke: "color-mix(in srgb, #60706b 50%, transparent)",
    strokeDasharray:
      "calc(2px * var(--rey-terrain-counter-scale)) calc(8px * var(--rey-terrain-counter-scale))",
    strokeWidth: "calc(0.7px * var(--rey-terrain-counter-scale))",
  },
  semanticGlobeLayer: {
    pointerEvents: "auto",
    zIndex: 2,
  },
  semanticGlobeAtmosphere: {
    filter:
      "drop-shadow(0 34px 42px color-mix(in srgb, #183d3a 28%, transparent)) drop-shadow(0 0 28px color-mix(in srgb, #fbefd1 36%, transparent))",
    pointerEvents: "none",
  },
  semanticGlobeSphere: {
    filter:
      "drop-shadow(0 24px 30px color-mix(in srgb, #20383d 24%, transparent))",
    stroke: "color-mix(in srgb, #8fa69d 56%, transparent)",
    strokeWidth: "calc(0.8px * var(--rey-terrain-counter-scale))",
  },
  semanticGlobeSamples: {
    fill: "none",
    opacity: 0.82,
    pointerEvents: "none",
    stroke: "color-mix(in srgb, #243b38 86%, #899b91)",
    strokeLinecap: "round",
    strokeWidth: "calc(1.6px * var(--rey-terrain-counter-scale))",
  },
  semanticGlobePolePattern: {
    opacity: 0.96,
    stroke: "#243b38",
  },
  semanticGlobeCluster: {
    fill: "color-mix(in srgb, #e8d18f 10%, transparent)",
    pointerEvents: "none",
    stroke: "color-mix(in srgb, #e1c36a 58%, transparent)",
    strokeDasharray:
      "calc(4px * var(--rey-terrain-counter-scale)) calc(6px * var(--rey-terrain-counter-scale))",
    strokeWidth: "calc(1px * var(--rey-terrain-counter-scale))",
  },
  semanticGlobeRegion: {
    cursor: "pointer",
    outline: {
      default: "none",
      ":focus-visible": "2px solid var(--rey-accent)",
    },
  },
  semanticGlobeRegionPoint: {
    fill: "color-mix(in srgb, #eef3db 76%, var(--rey-accent))",
    stroke: "color-mix(in srgb, #283f42 82%, var(--rey-foreground))",
    strokeWidth: "calc(1.8px * var(--rey-terrain-counter-scale))",
  },
  semanticGlobeRegionLabel: {
    fill: "#213532",
    fontFamily: mono,
    fontSize: "calc(16px * var(--rey-terrain-counter-scale))",
    fontWeight: 850,
    letterSpacing: "0.06em",
    paintOrder: "stroke",
    pointerEvents: "none",
    stroke: "color-mix(in srgb, #f4f2e8 94%, transparent)",
    strokeWidth: "calc(5px * var(--rey-terrain-counter-scale))",
  },
  semanticGlobeBeacon: {
    cursor: "pointer",
    outline: {
      default: "none",
      ":focus-visible": "2px solid var(--rey-accent)",
    },
    textDecoration: "none",
  },
  semanticGlobeSurveyBeacon: {
    filter:
      "drop-shadow(0 0 10px color-mix(in srgb, #f2a94d 72%, transparent))",
  },
  semanticGlobeBeaconHalo: {
    animationDuration: "2.4s",
    animationIterationCount: "infinite",
    animationName: {
      default: beaconPulse,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    fill: "color-mix(in srgb, #f2a94d 22%, transparent)",
    pointerEvents: "none",
    stroke: "color-mix(in srgb, #f2a94d 68%, transparent)",
    strokeWidth: "calc(1.2px * var(--rey-terrain-counter-scale))",
    transformBox: "fill-box",
    transformOrigin: "center",
  },
  semanticGlobeBeaconPoint: {
    fill: "#f2a94d",
    filter: "drop-shadow(0 0 8px color-mix(in srgb, #f2a94d 88%, transparent))",
    stroke: "#fff4cc",
    strokeWidth: "calc(2px * var(--rey-terrain-counter-scale))",
  },
  semanticGlobeBeaconLabel: {
    fill: "#182c29",
    fontFamily: mono,
    fontSize: "calc(14px * var(--rey-terrain-counter-scale))",
    fontWeight: 850,
    letterSpacing: "0.06em",
    paintOrder: "stroke",
    pointerEvents: "none",
    stroke: "color-mix(in srgb, #f7f3e8 96%, transparent)",
    strokeWidth: "calc(6px * var(--rey-terrain-counter-scale))",
    textTransform: "uppercase",
  },
  semanticGlobeBeaconState: {
    fill: "#875019",
    fontFamily: mono,
    fontSize: "calc(10px * var(--rey-terrain-counter-scale))",
    fontWeight: 800,
    letterSpacing: "0.09em",
    paintOrder: "stroke",
    pointerEvents: "none",
    stroke: "color-mix(in srgb, #f7f3e8 96%, transparent)",
    strokeWidth: "calc(5px * var(--rey-terrain-counter-scale))",
  },
  semanticGlobeBeaconLeader: {
    pointerEvents: "none",
    stroke: "color-mix(in srgb, #263c3a 72%, transparent)",
    strokeWidth: "calc(1px * var(--rey-terrain-counter-scale))",
  },
  semanticGlobeCaption: {
    fill: "var(--muted)",
    fontFamily: mono,
    fontSize: "calc(13px * var(--rey-terrain-counter-scale))",
    letterSpacing: "0.08em",
    pointerEvents: "none",
  },
  worldAtlasMorphLayer: {
    pointerEvents: "auto",
    zIndex: 3,
  },
  worldAtlasMorphSector: {
    fill: "color-mix(in srgb, var(--rey-accent) 8%, transparent)",
    pointerEvents: "none",
    stroke: "color-mix(in srgb, var(--rey-accent) 52%, var(--line))",
    strokeDasharray: "5 5",
    strokeWidth: 1.2,
  },
  worldAtlasMorphPoint: {
    cursor: "pointer",
    outline: { default: "none", ":focus-visible": "none" },
  },
  worldAtlasMorphMarker: {
    fill: "color-mix(in srgb, #eef3db 76%, var(--rey-accent))",
    stroke: "color-mix(in srgb, #283f42 82%, var(--rey-foreground))",
    strokeWidth: 1.8,
  },
  worldAtlasMorphLabel: {
    fill: "#213532",
    fontFamily: mono,
    // The growth factor multiplies on top of the counter-scale (which only
    // cancels the scene's own zoom curve) — see worldAtlasLabelGrowthScale.
    fontSize:
      "calc(8.64px * var(--rey-terrain-counter-scale) * var(--rey-world-atlas-label-growth, 1))",
    fontWeight: 800,
    paintOrder: "stroke",
    pointerEvents: "none",
    stroke: "color-mix(in srgb, var(--rey-background) 88%, transparent)",
    strokeWidth:
      "calc(5px * var(--rey-terrain-counter-scale) * var(--rey-world-atlas-label-growth, 1))",
  },
  atlasFeatureLayer: {
    pointerEvents: "auto",
    zIndex: 3,
  },
  atlasSector: {
    fill: "color-mix(in srgb, var(--rey-accent) 6%, transparent)",
    pointerEvents: "none",
    stroke: "color-mix(in srgb, var(--rey-accent) 48%, var(--line))",
    strokeDasharray: "5 5",
    strokeWidth: 1.2,
    vectorEffect: "non-scaling-stroke",
  },
  atlasFeature: {
    cursor: "pointer",
    outline: {
      default: "none",
      ":focus-visible": "2px solid var(--rey-accent)",
    },
  },
  atlasFeatureHalo: {
    fill: "color-mix(in srgb, var(--rey-accent) 12%, transparent)",
    stroke: "color-mix(in srgb, var(--rey-accent) 38%, transparent)",
    strokeWidth: 1,
    vectorEffect: "non-scaling-stroke",
  },
  atlasFeaturePoint: {
    fill: "#446c61",
    stroke: "#f4f0df",
    strokeWidth: 2,
    vectorEffect: "non-scaling-stroke",
  },
  atlasFeatureLabel: {
    fill: "#213532",
    fontFamily: mono,
    // Matches worldAtlasMorphLabel exactly (size, weight, halo color and
    // width) — this label is what that one hands off to the instant the
    // World<->Atlas morph reaches progress 1, so any difference between
    // the two reads as the label's glow visibly snapping to a new look at
    // that exact moment instead of the handoff being invisible. Same growth
    // factor too (see worldAtlasLabelGrowthScale) so size keeps climbing
    // continuously through the handoff instead of jumping to a flat value.
    fontSize:
      "calc(8.64px * var(--rey-terrain-counter-scale) * var(--rey-world-atlas-label-growth, 1))",
    fontWeight: 800,
    paintOrder: "stroke",
    pointerEvents: "none",
    stroke: "color-mix(in srgb, var(--rey-background) 88%, transparent)",
    strokeWidth:
      "calc(5px * var(--rey-terrain-counter-scale) * var(--rey-world-atlas-label-growth, 1))",
  },
  worldHorizon: {
    fill: "color-mix(in srgb, #78959b 5%, transparent)",
    opacity: 0.8,
    stroke: "color-mix(in srgb, #637d84 78%, var(--rey-foreground))",
    strokeDasharray:
      "calc(8px * var(--rey-terrain-counter-scale)) calc(7px * var(--rey-terrain-counter-scale))",
    strokeWidth: "calc(1.5px * var(--rey-terrain-counter-scale))",
  },
  chartedLand: {
    fill: "color-mix(in srgb, #8fa77b 18%, var(--rey-background))",
    opacity: 0.92,
    stroke: "color-mix(in srgb, #47604d 58%, var(--rey-foreground))",
    strokeWidth: "calc(1.2px * var(--rey-terrain-counter-scale))",
  },
  chartedLandAccelerated: {
    fill: "transparent",
    opacity: 0.72,
  },
  region: {
    alignContent: "start",
    backgroundColor: "color-mix(in srgb, var(--surface) 54%, transparent)",
    borderRadius: 18,
    borderStyle: "solid",
    borderWidth: 1,
    display: "grid",
    fontFamily: mono,
    fontSize: "0.62rem",
    gap: 4,
    gridAutoRows: "min-content",
    letterSpacing: "0.08em",
    padding: 16,
    position: "absolute",
    textTransform: "uppercase",
    zIndex: 0,
  },
  mapBoundary: {
    backgroundColor: "color-mix(in srgb, #89a76f 5%, transparent)",
    borderRadius: 46,
    borderStyle: "dashed",
    borderWidth: 1.5,
    color: "color-mix(in srgb, var(--rey-foreground) 75%, transparent)",
    pointerEvents: "none",
  },
  mapZone: {
    borderRadius: 28,
    fontSize: "0.5rem",
    opacity: 0.72,
    pointerEvents: "none",
  },
  worldUnexploredZone: {
    backgroundColor: "transparent",
    borderColor: "color-mix(in srgb, var(--muted) 38%, transparent)",
  },
  regionNeutral: { borderColor: "var(--line)" },
  regionAccent: {
    borderColor: "color-mix(in srgb, var(--rey-accent) 70%, transparent)",
  },
  regionAttention: {
    borderColor: "color-mix(in srgb, #b57417 70%, transparent)",
  },
  regionHealthy: {
    borderColor: "color-mix(in srgb, #237047 70%, transparent)",
  },
  regionUnknown: {
    backgroundColor: "color-mix(in srgb, var(--muted) 5%, transparent)",
    borderColor: "color-mix(in srgb, var(--muted) 70%, transparent)",
    borderStyle: "dashed",
  },
  regionOmitted: {
    backgroundColor: "color-mix(in srgb, #8a5a19 8%, transparent)",
    borderColor: "#8a5a19",
    borderStyle: "dashed",
  },
  regionStale: {
    backgroundColor: "color-mix(in srgb, #8255a6 8%, transparent)",
    borderColor: "#8255a6",
  },
  regionUnsupported: {
    backgroundColor: "color-mix(in srgb, #686868 8%, transparent)",
    borderColor: "#686868",
    borderStyle: "dotted",
  },
  regionFrontier: {
    backgroundColor: "color-mix(in srgb, var(--rey-accent) 7%, transparent)",
    borderColor: "var(--rey-accent)",
    borderStyle: "dashed",
  },
  reliefLayer: {
    height: "100%",
    inset: 0,
    overflow: "visible",
    pointerEvents: "none",
    position: "absolute",
    width: "100%",
    zIndex: 1,
  },
  reliefContour: {
    fill: "none",
    opacity: 0.62,
    stroke: "color-mix(in srgb, #566c49 72%, var(--rey-foreground))",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    strokeWidth: 1.15,
    vectorEffect: "non-scaling-stroke",
  },
  reliefContourLow: {
    opacity: 0.36,
    strokeDasharray: "3 3",
  },
  reliefContourPeak: {
    opacity: 0.88,
    stroke: "color-mix(in srgb, #2f4f36 84%, var(--rey-foreground))",
    strokeWidth: 1.55,
  },
  naturalFeatureLayer: {
    height: "100%",
    inset: 0,
    overflow: "visible",
    pointerEvents: "none",
    position: "absolute",
    width: "100%",
    zIndex: 2,
  },
  naturalFeatureGroup: {
    fill: "none",
    fontFamily: mono,
  },
  naturalFeature: {
    fill: "none",
    opacity: 0.7,
    strokeLinecap: "round",
    strokeLinejoin: "round",
  },
  streamFeature: {
    opacity: 0.56,
    stroke: "color-mix(in srgb, #56a5b6 72%, var(--rey-foreground))",
  },
  riverFeature: {
    opacity: 0.9,
    stroke: "color-mix(in srgb, #24758d 88%, var(--rey-foreground))",
  },
  weatherFront: {
    opacity: 0.76,
    stroke: "color-mix(in srgb, #8796a1 76%, #a36b16)",
    strokeDasharray:
      "calc(5px * var(--rey-terrain-counter-scale)) calc(6px * var(--rey-terrain-counter-scale))",
  },
  naturalFeatureLabel: {
    fill: "var(--rey-foreground)",
    fontFamily: mono,
    fontSize: "calc(8px * var(--rey-terrain-counter-scale))",
    fontWeight: 800,
    letterSpacing: "0.08em",
    paintOrder: "stroke",
    stroke: "var(--rey-background)",
    strokeWidth: "calc(4px * var(--rey-terrain-counter-scale))",
  },
  edgeLayer: {
    height: "100%",
    inset: 0,
    overflow: "visible",
    pointerEvents: "none",
    position: "absolute",
    width: "100%",
    zIndex: 1,
  },
  edgeGroup: {
    fill: "var(--muted)",
    fontFamily: mono,
    fontSize: 9,
    letterSpacing: "0.08em",
  },
  edge: {
    stroke: "color-mix(in srgb, var(--rey-foreground) 38%, transparent)",
    strokeWidth: 1.5,
    vectorEffect: "non-scaling-stroke",
  },
  edgeDirects: {
    stroke: "var(--rey-accent)",
    strokeWidth: 2.4,
  },
  edgeContains: { strokeDasharray: "6 5" },
  edgeLabel: {
    paintOrder: "stroke",
    stroke: "var(--rey-background)",
    strokeWidth: 5,
    vectorEffect: "non-scaling-stroke",
  },
  pointOfInterest: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--rey-foreground)",
    cursor: "pointer",
    display: "flex",
    font: "inherit",
    gap: 9,
    padding: 0,
    position: "absolute",
    textAlign: "left",
    transform: {
      default: "translate(-50%, -50%) scale(var(--rey-terrain-counter-scale))",
      ":hover":
        "translate(-50%, calc(-50% - 3px)) scale(var(--rey-terrain-counter-scale))",
    },
    transformOrigin: "center center",
    transitionDuration: {
      default: "140ms",
      "@media (prefers-reduced-motion: reduce)": "0.01ms",
    },
    transitionProperty: "transform",
    zIndex: 4,
    ":focus-visible": {
      outlineColor: "var(--rey-accent)",
      outlineOffset: 5,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
  },
  pointMarker: {
    backgroundColor: "var(--surface-strong)",
    borderColor: "#315a3e",
    borderRadius: "50% 50% 50% 0",
    borderStyle: "solid",
    borderWidth: 3,
    boxShadow:
      "0 3px 0 color-mix(in srgb, var(--rey-foreground) 18%, transparent), 0 7px 15px color-mix(in srgb, var(--rey-foreground) 18%, transparent)",
    display: "block",
    flex: "0 0 auto",
    height: 18,
    position: "relative",
    transform: "rotate(-45deg)",
    width: 18,
    "::after": {
      backgroundColor: "#315a3e",
      borderRadius: "50%",
      content: '\"\"',
      height: 5,
      left: 4,
      position: "absolute",
      top: 4,
      width: 5,
    },
  },
  prominentPoint: {
    zIndex: 5,
  },
  frontierPoint: {
    opacity: 0.88,
  },
  frontierMarker: {
    borderColor: "#9a681d",
    borderRadius: 3,
    transform: "rotate(45deg)",
    "::after": { backgroundColor: "#9a681d" },
  },
  pointFamily: {
    color: "var(--muted)",
    fontSize: "0.45rem",
    fontStyle: "normal",
    letterSpacing: "0.1em",
  },
  pointName: {
    fontFamily: display,
    fontSize: "0.76rem",
    fontWeight: 900,
    letterSpacing: "-0.01em",
    lineHeight: 1,
    textTransform: "uppercase",
  },
  pointDetail: {
    color: "var(--muted)",
    fontSize: "0.44rem",
    fontStyle: "normal",
    maxWidth: 195,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  pointSignal: {
    color: "#8a5a19",
    fontSize: "0.43rem",
    fontStyle: "normal",
    fontWeight: 800,
    letterSpacing: "0.05em",
  },
  pointAction: {
    color: "var(--rey-accent)",
    fontSize: "0.4rem",
    fontStyle: "normal",
    letterSpacing: "0.04em",
    maxWidth: 220,
    whiteSpace: "normal",
  },
  pointLabel: {
    backgroundColor:
      "color-mix(in srgb, var(--rey-background) 88%, transparent)",
    borderColor: "color-mix(in srgb, var(--line) 78%, transparent)",
    borderRadius: 4,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 4px 12px color-mix(in srgb, black 10%, transparent)",
    display: "grid",
    fontFamily: mono,
    gap: 2,
    maxWidth: 210,
    paddingBlock: 5,
    paddingInline: 7,
    whiteSpace: "nowrap",
  },
  topologyObject: {
    backgroundColor: "var(--surface-strong)",
    borderRadius: "var(--rey-radius)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: {
      default:
        "0 8px 0 color-mix(in srgb, var(--rey-foreground) 10%, transparent), 0 14px 24px color-mix(in srgb, var(--rey-foreground) 12%, transparent)",
      ":hover":
        "0 12px 0 color-mix(in srgb, var(--rey-foreground) 12%, transparent), 0 19px 31px color-mix(in srgb, var(--rey-foreground) 16%, transparent)",
      ":active": "inset 0 3px 8px color-mix(in srgb, black 15%, transparent)",
    },
    color: "var(--rey-foreground)",
    cursor: "pointer",
    display: "grid",
    font: "inherit",
    gap: 8,
    minHeight: 126,
    padding: 17,
    position: "absolute",
    textAlign: "left",
    textDecoration: "none",
    transform: {
      default: "translate(-50%, -50%)",
      ":hover": "translate(-50%, calc(-50% - 4px))",
      ":active": "translate(-50%, calc(-50% + 2px))",
    },
    transitionDuration: {
      default: "140ms",
      "@media (prefers-reduced-motion: reduce)": "0.01ms",
    },
    transitionProperty: "transform, box-shadow, border-color",
    transitionTimingFunction: "ease",
    zIndex: 3,
    ":focus-visible": {
      outlineColor: "var(--rey-accent)",
      outlineOffset: 4,
      outlineStyle: "solid",
      outlineWidth: 3,
    },
  },
  topologyObjectCulledLabel: {
    borderRadius: "50%",
    boxShadow:
      "0 3px 0 color-mix(in srgb, var(--rey-foreground) 14%, transparent)",
    height: 20,
    minHeight: 20,
    padding: 0,
  },
  culledLabelMarker: {
    backgroundColor: "currentColor",
    borderRadius: "50%",
    display: "block",
    height: 6,
    margin: "auto",
    width: 6,
  },
  objectNeutral: { borderColor: "var(--line)" },
  objectAccent: {
    borderColor: "var(--rey-accent)",
    borderTopWidth: 5,
  },
  objectHealthy: {
    borderColor: "#237047",
    borderTopWidth: 5,
  },
  objectAttention: {
    borderColor: "#b57417",
    borderTopWidth: 5,
  },
  objectBlocked: {
    borderColor: "#a3302a",
    borderTopWidth: 5,
  },
  objectUnknown: {
    borderColor: "var(--muted)",
    borderStyle: "dashed",
    borderTopWidth: 5,
  },
  objectOmitted: {
    borderColor: "#8a5a19",
    borderStyle: "dashed",
    borderTopWidth: 5,
  },
  objectStale: {
    borderColor: "#8255a6",
    borderTopWidth: 5,
  },
  objectUnsupported: {
    borderColor: "#686868",
    borderStyle: "dotted",
    borderTopWidth: 5,
  },
  objectFrontier: {
    borderColor: "var(--rey-accent)",
    borderStyle: "dashed",
    borderTopWidth: 5,
  },
  objectFamily: {
    color: "var(--muted)",
    fontFamily: mono,
    fontSize: "0.54rem",
    letterSpacing: "0.1em",
  },
  objectLabel: {
    fontFamily: display,
    fontSize: "1.18rem",
    fontWeight: 900,
    letterSpacing: "-0.025em",
    lineHeight: 1,
    overflowWrap: "anywhere",
    textTransform: "uppercase",
  },
  objectDetail: {
    color: "var(--muted)",
    fontFamily: mono,
    fontSize: "0.54rem",
    lineHeight: 1.35,
    overflowWrap: "anywhere",
    textTransform: "uppercase",
  },
  objectAction: {
    alignSelf: "end",
    color: "var(--rey-accent)",
    fontFamily: mono,
    fontSize: "0.5rem",
    fontWeight: 800,
    letterSpacing: "0.08em",
    marginTop: 4,
    textTransform: "uppercase",
  },
  canvasCoordinates: {
    bottom: 14,
    color: "var(--muted)",
    display: "grid",
    fontFamily: mono,
    fontSize: "0.52rem",
    gap: 4,
    left: 16,
    letterSpacing: "0.08em",
    pointerEvents: "none",
    position: "absolute",
    transitionDuration: {
      default: "260ms",
      "@media (prefers-reduced-motion: reduce)": "0.01ms",
    },
    transitionProperty: "transform",
    transitionTimingFunction: "cubic-bezier(.2,.8,.2,1)",
    zIndex: 5,
  },
  canvasCoordinatesFooterVisible: {
    transform: "translateY(-48px)",
  },
  lensLegend: {
    alignItems: "center",
    backgroundColor:
      "color-mix(in srgb, var(--rey-background) 88%, transparent)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    display: { default: "flex", "@media (max-width: 760px)": "none" },
    gap: 8,
    paddingBlock: 8,
    paddingInline: 12,
    pointerEvents: "none",
    position: "absolute",
    right: 14,
    top: 14,
    zIndex: 5,
  },
  landscapeLensLegend: {
    backgroundColor:
      "color-mix(in srgb, var(--rey-background) 66%, transparent)",
    borderColor: "color-mix(in srgb, var(--line) 58%, transparent)",
    opacity: 0.7,
  },
  lensStep: {
    alignItems: "center",
    color: "var(--muted)",
    display: "flex",
    fontFamily: mono,
    fontSize: "0.48rem",
    gap: 6,
    letterSpacing: "0.07em",
    "::before": {
      borderColor: "var(--muted)",
      borderRadius: "50%",
      borderStyle: "solid",
      borderWidth: 1,
      content: '""',
      height: 6,
      width: 6,
    },
  },
  lensStepActive: {
    color: "var(--rey-foreground)",
    fontWeight: 800,
    "::before": {
      backgroundColor: "var(--rey-accent)",
      borderColor: "var(--rey-accent)",
    },
  },
  legendLine: { backgroundColor: "var(--line)", height: 1, width: 18 },
  mapReading: {
    alignItems: "end",
    bottom: 14,
    display: "grid",
    gap: 7,
    maxWidth: 390,
    pointerEvents: "none",
    position: "absolute",
    right: 14,
    zIndex: 6,
  },
  landscapeMapReading: {
    maxWidth: 280,
    opacity: 0.68,
  },
  bearingCard: {
    backgroundColor:
      "color-mix(in srgb, var(--rey-background) 91%, transparent)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 8px 22px color-mix(in srgb, black 10%, transparent)",
    display: "grid",
    fontFamily: mono,
    gap: 4,
    paddingBlock: 9,
    paddingInline: 11,
    textAlign: "right",
    textTransform: "uppercase",
  },
  bearingEyebrow: {
    color: "var(--muted)",
    fontSize: "0.43rem",
    letterSpacing: "0.1em",
  },
  bearingTitle: {
    fontFamily: display,
    fontSize: "0.75rem",
    letterSpacing: "0.01em",
  },
  bearingDetail: {
    color: "var(--muted)",
    fontSize: "0.43rem",
    lineHeight: 1.35,
  },
  orientationGuide: {
    backdropFilter: "blur(18px)",
    backgroundColor: "color-mix(in srgb, #f2f0e7 88%, transparent)",
    borderColor: "color-mix(in srgb, #476b63 46%, transparent)",
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 14px 34px color-mix(in srgb, #1e3e38 16%, transparent)",
    color: "#1c302d",
    display: "grid",
    fontFamily: mono,
    gap: 9,
    paddingBlock: 14,
    paddingInline: 16,
    textAlign: "left",
    textTransform: "uppercase",
  },
  orientationActions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 3,
  },
  orientationAction: {
    borderColor: "color-mix(in srgb, #42675f 58%, transparent)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "#294d46",
    fontSize: "0.45rem",
    fontWeight: 850,
    letterSpacing: "0.07em",
    paddingBlock: 7,
    paddingInline: 9,
    pointerEvents: "auto",
    textDecoration: "none",
  },
  consentAction: {
    backgroundColor: "#294f48",
    color: "#f5f0df",
  },
  orientationMapReading: {
    alignItems: "stretch",
    bottom: 22,
    left: "clamp(16px, 3vw, 44px)",
    maxWidth: 420,
    right: "auto",
    width: "min(calc(100% - 32px), 420px)",
  },
  orientationBoundary: {
    color: "#5e706b",
    fontFamily: mono,
    fontSize: "0.43rem",
    letterSpacing: "0.08em",
    textAlign: "center",
  },
  orientationCoordinates: {
    color: "#586a66",
  },
  orientationLensLegend: {
    backgroundColor: "color-mix(in srgb, #f3f1e8 80%, transparent)",
    backdropFilter: "blur(14px)",
  },
  mapKey: {
    alignItems: "center",
    backgroundColor:
      "color-mix(in srgb, var(--rey-background) 87%, transparent)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flexWrap: "wrap",
    fontFamily: mono,
    fontSize: "0.42rem",
    gap: 10,
    justifyContent: "end",
    letterSpacing: "0.06em",
    paddingBlock: 7,
    paddingInline: 9,
  },
  keyContour: {
    borderTopColor: "#566c49",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "inline-block",
    marginRight: 3,
    verticalAlign: "middle",
    width: 20,
  },
  keyStream: {
    borderTopColor: "#56a5b6",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "inline-block",
    marginRight: 3,
    verticalAlign: "middle",
    width: 20,
  },
  keyRiver: {
    backgroundColor: "#24758d",
    display: "inline-block",
    height: 3,
    marginRight: 3,
    verticalAlign: "middle",
    width: 20,
  },
  keyWeather: {
    borderTopColor: "#8796a1",
    borderTopStyle: "dashed",
    borderTopWidth: 2,
    display: "inline-block",
    marginRight: 3,
    verticalAlign: "middle",
    width: 20,
  },
  mapScale: {
    alignItems: "end",
    color: "var(--muted)",
    display: "grid",
    fontFamily: mono,
    fontSize: "0.41rem",
    gap: 3,
    justifyItems: "end",
    letterSpacing: "0.06em",
    textTransform: "uppercase",
  },
  mapScaleBar: {
    borderBottomColor: "var(--rey-foreground)",
    borderBottomStyle: "solid",
    borderBottomWidth: 2,
    borderLeftColor: "var(--rey-foreground)",
    borderLeftStyle: "solid",
    borderLeftWidth: 1,
    borderRightColor: "var(--rey-foreground)",
    borderRightStyle: "solid",
    borderRightWidth: 1,
    height: 6,
    width: 120,
  },
  canvasFooter: {
    alignItems: "center",
    backdropFilter: "blur(14px)",
    backgroundColor:
      "color-mix(in srgb, var(--rey-background) 94%, transparent)",
    borderTopColor: "transparent",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    boxSizing: "border-box",
    boxShadow:
      "0 -10px 28px color-mix(in srgb, var(--rey-foreground) 10%, transparent)",
    bottom: 0,
    display: "flex",
    fontFamily: mono,
    fontSize: "0.5rem",
    justifyContent: "center",
    letterSpacing: "0.07em",
    maxHeight: 0,
    minHeight: 0,
    opacity: 0,
    overflow: "hidden",
    paddingBlock: 0,
    paddingInline: 14,
    pointerEvents: "none",
    position: "absolute",
    insetInline: 0,
    textAlign: "center",
    textTransform: "uppercase",
    transform: "translateY(100%)",
    transitionDuration: {
      default: "260ms",
      "@media (prefers-reduced-motion: reduce)": "0.01ms",
    },
    transitionProperty:
      "max-height, min-height, opacity, padding, transform, border-color",
    transitionTimingFunction: "cubic-bezier(.2,.8,.2,1)",
    willChange: "max-height, opacity, transform",
    zIndex: 9,
  },
  canvasFooterVisible: {
    borderTopColor: "var(--line)",
    maxHeight: 72,
    minHeight: 34,
    opacity: 1,
    paddingBlock: 8,
    pointerEvents: "auto",
    transform: "translateY(0)",
  },
  canvasFooterAttention: {
    color: "var(--rey-foreground)",
  },
  canvasFooterNotice: {
    lineHeight: 1.4,
    maxWidth: "min(78vw, 980px)",
  },
  canvasFooterNoticeWithCoordinate: {
    maxWidth: "min(48vw, 720px)",
  },
  orientationCanvasFooter: {
    backgroundColor: "color-mix(in srgb, #e3e4de 88%, transparent)",
    color: "#65736f",
  },
  coordinateUri: {
    color: "var(--muted)",
    display: { default: "block", "@media (max-width: 980px)": "none" },
    maxWidth: "25vw",
    overflow: "hidden",
    position: "absolute",
    right: 14,
    textOverflow: "ellipsis",
    top: "50%",
    transform: "translateY(-50%)",
    whiteSpace: "nowrap",
  },
});
