import * as stylex from "@stylexjs/stylex";

const mono = 'var(--mono, "SFMono-Regular", Consolas, monospace)';

export const journalStyles = stylex.create({
  page: { paddingTop: "clamp(46px, 6vw, 88px)" },
  entries: { display: "grid", gap: 24, marginTop: 28 },
  entry: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
  },
  entryHeader: {
    alignItems: "start",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 18,
    gridTemplateColumns: {
      default: "74px minmax(0, 1fr) auto",
      "@media (max-width: 680px)": "58px minmax(0, 1fr)",
    },
    padding: "22px 24px",
  },
  entryLink: {
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--surface-strong)",
    },
    color: "inherit",
    textDecoration: "none",
  },
  entrySelection: {
    alignItems: "end",
    display: "grid",
    fontFamily: mono,
    fontSize: "0.64rem",
    gap: 12,
    justifyItems: "end",
  },
  entryOrdinal: {
    alignItems: "center",
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    display: "flex",
    fontFamily: mono,
    fontSize: "0.72rem",
    height: 52,
    justifyContent: "center",
  },
  entryIdentity: { display: "grid", gap: 6, minWidth: 0 },
  blockStack: { display: "grid", gap: 1, backgroundColor: "var(--line)" },
  broadsheet: { backgroundColor: "var(--line)", display: "grid", gap: 1 },
  broadsheetBand: {
    alignItems: "stretch",
    display: "grid",
    gap: 1,
    gridTemplateColumns: {
      default: "repeat(12, minmax(0, 1fr))",
      "@media (max-width: 760px)": "minmax(0, 1fr)",
    },
  },
  broadsheetCell: {
    display: "grid",
    gridColumn: { "@media (max-width: 760px)": "1 !important" },
    minWidth: 0,
  },
  block: {
    backgroundColor: "var(--surface)",
    minWidth: 0,
    padding: "24px 26px",
    scrollMarginTop: 118,
  },
  blockHeader: {
    alignItems: "center",
    color: "var(--muted)",
    display: "flex",
    gap: 16,
    justifyContent: "space-between",
    marginBottom: 18,
  },
  blockPermalink: { color: "inherit", textDecoration: "none" },
  proseBlock: { backgroundColor: "var(--surface-strong)" },
  proseDocument: { lineHeight: 1.72, maxWidth: 900 },
  exploreBlock: { display: "grid", gap: 13 },
  coordinate: { overflowWrap: "anywhere" },
  exploreLink: {
    borderBottomColor: "currentColor",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    color: "inherit",
    fontFamily: mono,
    fontSize: "0.64rem",
    justifySelf: "start",
    paddingBottom: 5,
    textDecoration: "none",
  },
  queryBlock: { backgroundColor: "#171a1a", color: "#f1f0e8" },
  queryMeta: {
    display: "flex",
    flexWrap: "wrap",
    fontFamily: mono,
    fontSize: "0.65rem",
    gap: 18,
  },
  codeSurface: {
    backgroundColor: "#0c0e0e",
    borderColor: "#4b5050",
    borderStyle: "solid",
    borderWidth: 1,
    color: "#e7e5d8",
    fontFamily: mono,
    lineHeight: 1.6,
    marginBottom: 0,
    overflowX: "auto",
    padding: 20,
    whiteSpace: "pre-wrap",
  },
  frameMeta: { display: "flex", gap: 18, justifyContent: "space-between" },
  frameScroll: { overflowX: "auto" },
  frameTable: {
    borderCollapse: "collapse",
    fontFamily: mono,
    fontSize: "0.7rem",
    marginTop: 16,
    width: "100%",
  },
  diffBlock: {
    borderLeftColor: "#9a3c25",
    borderLeftStyle: "solid",
    borderLeftWidth: 5,
  },
  actionBlock: {
    borderLeftColor: "#237047",
    borderLeftStyle: "solid",
    borderLeftWidth: 5,
  },
  entryBinding: {
    alignItems: "center",
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    flexWrap: "wrap",
    gap: 20,
    justifyContent: "space-between",
    padding: "16px 24px",
  },
  composeButton: {
    appearance: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--surface)",
    },
    borderColor: "var(--line)",
    borderStyle: "dashed",
    borderWidth: 1,
    color: "var(--rey-foreground)",
    cursor: "pointer",
    display: "grid",
    fontFamily: "inherit",
    gap: 9,
    marginTop: 14,
    opacity: 1,
    padding: 48,
    textAlign: "center",
    textDecoration: "none",
    width: "100%",
  },
  composer: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--rey-foreground)",
    borderStyle: "solid",
    borderWidth: 2,
    marginTop: 28,
  },
  liveDocument: { marginTop: 28 },
  liveHeader: { alignItems: "center" },
  inlineLabel: { display: "flex", flexWrap: "wrap", gap: 8 },
  inlineMetaControl: {
    appearance: "none",
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--muted)",
    fontFamily: mono,
    fontSize: "0.64rem",
    minWidth: 80,
    outline: "none",
    padding: 0,
  },
  titleControl: {
    appearance: "none",
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--rey-foreground)",
    fontFamily:
      'var(--display, "Arial Narrow", "Roboto Condensed", sans-serif)',
    fontSize: "clamp(1.55rem, 4vw, 2.75rem)",
    fontWeight: 800,
    lineHeight: 0.94,
    minWidth: 0,
    outline: "none",
    padding: 0,
    width: "100%",
  },
  deltaSummary: {
    alignItems: "end",
    display: "grid",
    fontFamily: mono,
    fontSize: "0.68rem",
    gap: 5,
    justifyItems: "end",
  },
  cellTools: {
    alignItems: "center",
    backgroundColor: "var(--surface-strong)",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "flex-end",
    minHeight: 34,
    padding: "5px 8px",
  },
  deltaBadge: {
    color: "var(--muted)",
    fontFamily: mono,
    fontSize: "0.57rem",
    marginRight: "auto",
    textTransform: "uppercase",
  },
  cellSelect: {
    appearance: "none",
    backgroundColor: "transparent",
    borderColor: "currentColor",
    borderStyle: "solid",
    borderWidth: 1,
    color: "inherit",
    fontFamily: mono,
    fontSize: "0.61rem",
    padding: "5px 20px 5px 7px",
  },
  cellToolButton: {
    appearance: "none",
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "inherit",
    cursor: "pointer",
    fontFamily: mono,
    fontSize: "0.59rem",
    padding: 5,
  },
  visuallyHidden: {
    height: 1,
    margin: -1,
    overflow: "hidden",
    padding: 0,
    position: "absolute",
    width: 1,
  },
  liveText: {
    appearance: "none",
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "inherit",
    fontFamily: "inherit",
    fontSize: "0.92rem",
    lineHeight: 1.72,
    minHeight: 130,
    outline: "none",
    resize: "vertical",
    width: "100%",
  },
  proseLiveText: { fontSize: "1rem", maxWidth: 900 },
  liveCode: {
    minHeight: 160,
    resize: "vertical",
    width: "100%",
  },
  darkInlineControl: {
    appearance: "none",
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "inherit",
    fontFamily: mono,
    fontSize: "0.65rem",
    outline: "none",
    padding: 0,
  },
  inlineFields: {
    alignItems: "center",
    display: "grid",
    gap: 10,
    gridTemplateColumns: {
      default: "minmax(0, 1fr) auto minmax(0, 1fr)",
      "@media (max-width: 680px)": "1fr",
    },
    marginBottom: 18,
  },
  inlineControl: {
    appearance: "none",
    backgroundColor: "transparent",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 0,
    borderBottomWidth: 1,
    color: "inherit",
    fontFamily: mono,
    fontSize: "0.7rem",
    minWidth: 0,
    outline: "none",
    padding: "8px 0",
    width: "100%",
  },
  operationControl: {
    appearance: "none",
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "inherit",
    fontFamily:
      'var(--display, "Arial Narrow", "Roboto Condensed", sans-serif)',
    fontSize: "1.55rem",
    fontWeight: 800,
    outline: "none",
    padding: 0,
    textTransform: "uppercase",
    width: "100%",
  },
  referenceEditors: {
    display: "grid",
    gap: 18,
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 680px)": "1fr",
    },
    marginTop: 16,
  },
  referenceEditor: { display: "grid", gap: 8 },
  referenceText: {
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    fontFamily: mono,
    fontSize: "0.67rem",
    minHeight: 76,
    padding: 10,
  },
  addCellBar: {
    alignItems: "center",
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    flexWrap: "wrap",
    gap: 14,
    padding: 18,
  },
  liveFooter: { backgroundColor: "var(--surface-strong)" },
  bindingIdentity: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 16,
  },
  revisionActions: { display: "flex", gap: 10 },
  authorityNote: {
    margin: 0,
    padding: "0 24px 18px",
    textAlign: "right",
  },
  composerHeader: {
    alignItems: "start",
    backgroundColor: "var(--rey-foreground)",
    color: "var(--rey-background)",
    display: "flex",
    justifyContent: "space-between",
    padding: "22px 26px",
  },
  composerMeta: {
    display: "grid",
    gap: 1,
    gridTemplateColumns: {
      default: "0.4fr 1fr",
      "@media (max-width: 700px)": "1fr",
    },
  },
  field: { display: "grid", gap: 10, padding: "22px 26px" },
  control: {
    backgroundColor: "var(--rey-background)",
    borderColor: "var(--line)",
    borderStyle: "solid",
    borderWidth: 1,
    color: "var(--rey-foreground)",
    fontFamily: "inherit",
    fontSize: "0.9rem",
    lineHeight: 1.5,
    outline: { default: "none", ":focus": "2px solid var(--rey-foreground)" },
    outlineOffset: 2,
    padding: "11px 13px",
    width: "100%",
  },
  textControl: { minHeight: 120, resize: "vertical" },
  queryControl: {
    backgroundColor: "#0c0e0e",
    borderColor: "#4b5050",
    color: "#f1f0e8",
    fontFamily: mono,
  },
  editorCell: { display: "grid", gap: 12, padding: 26 },
  bindingCell: {
    backgroundColor: "var(--surface-strong)",
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "grid",
    gap: 10,
    overflowWrap: "anywhere",
    padding: 22,
  },
  queryComposer: {
    backgroundColor: "#171a1a",
    color: "#f1f0e8",
    display: "grid",
    gap: 1,
  },
  addCell: {
    backgroundColor: "transparent",
    borderColor: "var(--line)",
    borderStyle: "dashed",
    borderWidth: 1,
    cursor: "pointer",
    fontFamily: mono,
    margin: 22,
    padding: 22,
  },
  composerError: { color: "#9a3c25", margin: 0, padding: "0 26px 20px" },
  textButton: {
    appearance: "none",
    backgroundColor: "transparent",
    borderColor: "currentColor",
    borderStyle: "solid",
    borderWidth: 1,
    color: "inherit",
    cursor: "pointer",
    fontFamily: mono,
    fontSize: "0.64rem",
    padding: "10px 13px",
  },
  submitButton: {
    appearance: "none",
    backgroundColor: {
      default: "var(--rey-foreground)",
      ":disabled": "var(--line)",
    },
    borderWidth: 0,
    color: {
      default: "var(--rey-background)",
      ":disabled": "var(--muted)",
    },
    cursor: { default: "pointer", ":disabled": "wait" },
    fontFamily: mono,
    fontSize: "0.67rem",
    padding: "13px 16px",
  },
  composerFooter: {
    alignItems: "center",
    borderTopColor: "var(--line)",
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "flex",
    gap: 20,
    justifyContent: "space-between",
    padding: "20px 26px",
  },
  documentNav: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    marginBlock: 28,
  },
  revisionTrail: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    fontFamily: mono,
    fontSize: "0.68rem",
    gap: 14,
    justifyContent: "center",
  },
  routeHeading: {
    alignItems: "end",
    borderBottomColor: "var(--line)",
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 20,
    gridTemplateColumns: {
      default: "92px minmax(0, 1fr) auto",
      "@media (max-width: 700px)": "62px minmax(0, 1fr)",
    },
    paddingBottom: 17,
  },
  routeIndex: {
    fontFamily:
      'var(--display, "Arial Narrow", "Roboto Condensed", sans-serif)',
    fontSize: "2.8rem",
    fontWeight: 900,
    lineHeight: 0.8,
  },
  routeKicker: { marginBlock: 0, marginBottom: 5 },
});
