[package]
name = "rey"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "rey"
path = "src/main.rs"

[dependencies]
chrono.workspace = true
clap.workspace = true
rey-core = { path = "../rey-core" }
rey-diff = { path = "../rey-diff" }
rey-environment = { path = "../rey-environment" }
rey-git = { path = "../rey-git" }
rey-mining = { path = "../rey-mining" }
rey-runtime = { path = "../rey-runtime" }
serde.workspace = true
serde_json.workspace = true
serde-saphyr.workspace = true
thiserror.workspace = true
tiny_http.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
